
-- ============================================================
-- MfgPulse AI: Turn on all tasks and database components
-- ============================================================

-- 1. Resume child tasks FIRST (bottom-up order)
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_SNAPSHOT_KPIS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_ARCHIVE_ALERTS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CHECK_DRIFT RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CONVERT_PPOS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_GENERATE_POS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_GENERATE_WOS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_REFRESH_DTS RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_REFRESH_FATIGUE RESUME;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CHECK_FRESHNESS RESUME;

-- 2. Resume root task LAST (starts the DAG)
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG RESUME;

-- 3. Resume warehouse
ALTER WAREHOUSE MFGPULSE_AUTOMATION_WH RESUME IF SUSPENDED;

-- 4. Database settings
ALTER DATABASE FAILURE_GENOME_DB SET DATA_RETENTION_TIME_IN_DAYS = 1;

-- 1. Resume child tasks FIRST (bottom-up order)
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_SNAPSHOT_KPIS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_ARCHIVE_ALERTS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CHECK_DRIFT SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CONVERT_PPOS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_GENERATE_POS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_GENERATE_WOS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_REFRESH_DTS SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_REFRESH_FATIGUE SUSPEND;
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.DAG_CHECK_FRESHNESS SUSPEND;

-- 2. Resume root task LAST (starts the DAG)
ALTER TASK FAILURE_GENOME_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG SUSPEND;

-- 3. Resume warehouse
ALTER WAREHOUSE MFGPULSE_AUTOMATION_WH SUSPEND;
ALTER WAREHOUSE COMPUTE_WH SUSPEND;

SELECT GET_DDL('DATABASE','FAILURE_GENOME_DB');

--Validate replication group status and monitor initial sync progress on target account QEIPXIJ.NB44213

-- As ORGADMIN: enable replication for both accounts
SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('DGTEFBJ.JB14149', 'ENABLE_ACCOUNT_DATABASE_REPLICATION', 'true');
SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('DGTEFBJ.NB44213', 'ENABLE_ACCOUNT_DATABASE_REPLICATION', 'true');

-- As ACCOUNTADMIN: create replication group
CREATE REPLICATION GROUP MFGPULSE_REPLICATION
  OBJECT_TYPES = DATABASES
  ALLOWED_DATABASES = FAILURE_GENOME_DB
  ALLOWED_ACCOUNTS = DGTEFBJ.NB44213
  REPLICATION_SCHEDULE = '60 MINUTE';

--On target account (NB44213): Create secondary group and initial refresh
  USE ROLE ACCOUNTADMIN;
CREATE REPLICATION GROUP MFGPULSE_REPLICATION
  AS REPLICA OF DGTEFBJ.JB14149.MFGPULSE_REPLICATION;
ALTER REPLICATION GROUP MFGPULSE_REPLICATION REFRESH;

USE ROLE ACCOUNTADMIN;
CREATE REPLICATION GROUP MFGPULSE_REPLICATION
  AS REPLICA OF DGTEFBJ.JB14149.MFGPULSE_REPLICATION;
ALTER REPLICATION GROUP MFGPULSE_REPLICATION REFRESH;

CREATE OR REPLACE SHARE MFGPULSE_SHARE COMMENT = 'MFGPulse AI — Predictive Maintenance & OEE Command Center (read-only)'
GRANT USAGE ON DATABASE FAILURE_GENOME_DB TO SHARE MFGPULSE_SHARE

GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.RAW_OT TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.RAW_IT TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.CURATED TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.ML_FEATURES TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.ML_MODELS TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA FAILURE_GENOME_DB.ANALYTICS TO SHARE MFGPULSE_SHARE

SELECT TABLE_SCHEMA, TABLE_NAME FROM FAILURE_GENOME_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%FAILURE%' OR TABLE_NAME ILIKE '%REPAIR%' OR TABLE_NAME ILIKE '%COST%'
ORDER BY TABLE_SCHEMA

SELECT TABLE_NAME FROM FAILURE_GENOME_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW_IT' AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME

GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_OT.ASSET_MASTER TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_OT.SENSOR_METADATA TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_OT.SENSOR_READINGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_OT.AMBIENT_CONDITIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.WORK_ORDERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.MAINTENANCE_LOGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PARTS_INVENTORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PRODUCTION_OUTPUT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.SUPPLIERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.USERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PURCHASE_ORDERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PURCHASE_ORDER_LINES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.SHIFT_SCHEDULE TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.APP_NOTIFICATIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.NOTIFICATION_SETTINGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PART_RESERVATIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.SIMULATION_CONFIG TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.RAW_IT.PART_SUPPLIERS TO SHARE MFGPULSE_SHARE

-- CURATED
GRANT SELECT ON TABLE FAILURE_GENOME_DB.CURATED.SENSOR_WITH_CONTEXT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.CURATED.ASSET_HEALTH_CURRENT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.CURATED.FAILURE_HISTORY TO SHARE MFGPULSE_SHARE;
-- ML_FEATURES
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.ROLLING_STATS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.SENSOR_INTERACTIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.PHYSICS_COMPOSITE TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.TEMPORAL_MEMORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.CROSS_DOMAIN TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.FLEET_COMPARISON TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_FEATURES.LABELED_DATA TO SHARE MFGPULSE_SHARE;
-- ML_MODELS
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.LIVE_PREDICTIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.FATIGUE_SCORES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.ANOMALY_SCORES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.MODEL_REGISTRY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.FEEDBACK_LOG TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ML_MODELS.DRIFT_COMPARISON TO SHARE MFGPULSE_SHARE;
-- ANALYTICS
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ANALYTICS.ACTIVE_ALERTS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ANALYTICS.OEE_METRICS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ANALYTICS.SHIFT_HANDOVER_HISTORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ANALYTICS.KPI_SNAPSHOTS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE FAILURE_GENOME_DB.ANALYTICS.ALERT_HISTORY TO SHARE MFGPULSE_SHARE

GRANT SELECT ON VIEW FAILURE_GENOME_DB.ML_MODELS.DRIFT_METRICS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON VIEW FAILURE_GENOME_DB.ML_MODELS.MODEL_ACCURACY_LIVE TO SHARE MFGPULSE_SHARE
GRANT SELECT ON VIEW FAILURE_GENOME_DB.ML_MODELS.DRIFT_METRICS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON VIEW FAILURE_GENOME_DB.ML_MODELS.MODEL_ACCURACY_LIVE TO SHARE MFGPULSE_SHARE

ALTER SHARE MFGPULSE_SHARE ADD ACCOUNTS = QEIPXIJ.NB44213
SHOW GRANTS TO SHARE MFGPULSE_SHARE

SHOW GRANTS TO SHARE MFGPULSE_SHARE