-- ============================================================================
-- MFGPulse AI Test Suite: TC-01 Data Integrity
-- Validates schema existence, row counts, referential integrity, date ranges
-- ============================================================================
-- Usage: Run each SELECT individually or as a batch from Admin Panel

-- TC-01-01: All 7 schemas exist
SELECT 'TC-01-01' AS TEST_ID, 'Schema existence' AS TEST_NAME,
    7 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 7 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('RAW_OT','RAW_IT','CURATED','ML_FEATURES','ML_MODELS','ANALYTICS','AGENT');

-- TC-01-02: Asset master has 10 assets
SELECT 'TC-01-02' AS TEST_ID, 'Asset master count' AS TEST_NAME,
    10 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 10 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_OT.ASSET_MASTER;

-- TC-01-03: Sensor readings > 170K
SELECT 'TC-01-03' AS TEST_ID, 'Sensor readings volume' AS TEST_NAME,
    170000 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) > 170000 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_OT.SENSOR_READINGS;

-- TC-01-04: Users table has 9 active users (6 personas)
SELECT 'TC-01-04' AS TEST_ID, 'Active user count' AS TEST_NAME,
    9 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 9 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_IT.USERS WHERE ACTIVE = TRUE;

-- TC-01-05: All 6 personas represented
SELECT 'TC-01-05' AS TEST_ID, 'Persona coverage' AS TEST_NAME,
    6 AS EXPECTED, COUNT(DISTINCT PERSONA) AS ACTUAL,
    CASE WHEN COUNT(DISTINCT PERSONA) = 6 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_IT.USERS WHERE ACTIVE = TRUE;

-- TC-01-06: Zero orphaned sensor readings (FK to ASSET_MASTER)
SELECT 'TC-01-06' AS TEST_ID, 'Sensor→Asset referential integrity' AS TEST_NAME,
    0 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_OT.SENSOR_READINGS sr
LEFT JOIN MFGPULSE_DB.RAW_OT.ASSET_MASTER am ON sr.ASSET_ID = am.ASSET_ID
WHERE am.ASSET_ID IS NULL;

-- TC-01-07: Zero orphaned work orders
SELECT 'TC-01-07' AS TEST_ID, 'WO→Asset referential integrity' AS TEST_NAME,
    0 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS wo
LEFT JOIN MFGPULSE_DB.RAW_OT.ASSET_MASTER am ON wo.ASSET_ID = am.ASSET_ID
WHERE am.ASSET_ID IS NULL;

-- TC-01-08: No null primary keys on key tables
SELECT 'TC-01-08' AS TEST_ID, 'No null PKs' AS TEST_NAME,
    0 AS EXPECTED, SUM(NULL_CNT) AS ACTUAL,
    CASE WHEN SUM(NULL_CNT) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT COUNT_IF(ASSET_ID IS NULL) AS NULL_CNT FROM MFGPULSE_DB.RAW_OT.ASSET_MASTER
    UNION ALL SELECT COUNT_IF(USER_ID IS NULL) FROM MFGPULSE_DB.RAW_IT.USERS
    UNION ALL SELECT COUNT_IF(WO_ID IS NULL) FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS
    UNION ALL SELECT COUNT_IF(PART_ID IS NULL) FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY
    UNION ALL SELECT COUNT_IF(SUPPLIER_ID IS NULL) FROM MFGPULSE_DB.RAW_IT.SUPPLIERS
);

-- TC-01-09: All seed data within Mar-Sep 2026
SELECT 'TC-01-09' AS TEST_ID, 'Date range validation' AS TEST_NAME,
    0 AS EXPECTED, SUM(OUT_OF_RANGE) AS ACTUAL,
    CASE WHEN SUM(OUT_OF_RANGE) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT CASE WHEN MIN(CREATED_DATE)::DATE < '2026-03-01' OR MAX(CREATED_DATE)::DATE > '2026-09-30' THEN 1 ELSE 0 END AS OUT_OF_RANGE FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS
    UNION ALL SELECT CASE WHEN MIN(TIMESTAMP)::DATE < '2026-03-01' OR MAX(TIMESTAMP)::DATE > '2026-09-30' THEN 1 ELSE 0 END FROM MFGPULSE_DB.RAW_IT.MAINTENANCE_LOGS
    UNION ALL SELECT CASE WHEN MIN(TIMESTAMP)::DATE < '2026-03-01' OR MAX(TIMESTAMP)::DATE > '2026-09-30' THEN 1 ELSE 0 END FROM MFGPULSE_DB.RAW_IT.PRODUCTION_OUTPUT
);

-- TC-01-10: All data-bearing tables have data (excludes operational log tables that start empty)
SELECT 'TC-01-10' AS TEST_ID, 'DTs have data' AS TEST_NAME,
    0 AS EXPECTED,
    (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
     WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA IN ('CURATED','ML_FEATURES','ML_MODELS','ANALYTICS')
     AND TABLE_NAME NOT IN ('SHIFT_HANDOVER_HISTORY','BULK_OPERATION_LOG','ALERT_HISTORY')
     AND ROW_COUNT = 0) AS ACTUAL,
    CASE WHEN (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
     WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA IN ('CURATED','ML_FEATURES','ML_MODELS','ANALYTICS')
     AND TABLE_NAME NOT IN ('SHIFT_HANDOVER_HISTORY','BULK_OPERATION_LOG','ALERT_HISTORY')
     AND ROW_COUNT = 0) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS;

-- TC-01-11: Model registry has 12 models
SELECT 'TC-01-11' AS TEST_ID, 'Model registry count' AS TEST_NAME,
    12 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 12 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.ML_MODELS.MODEL_REGISTRY;

-- TC-01-12: Notification settings seeded (16 event types)
SELECT 'TC-01-12' AS TEST_ID, 'Notification settings seeded' AS TEST_NAME,
    16 AS EXPECTED, COUNT(*) AS ACTUAL,
    CASE WHEN COUNT(*) = 16 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS;
