-- ============================================================================
-- MFGPulse AI Test Suite: TC-03 Procurement
-- ============================================================================
SELECT 'TC-03-01' AS TEST_ID, 'ATP calculation' AS TEST_NAME, 0 AS EXPECTED, COUNT_IF(AVAILABLE_TO_PROMISE!=QUANTITY_ON_HAND-RESERVED_QUANTITY) AS ACTUAL, CASE WHEN COUNT_IF(AVAILABLE_TO_PROMISE!=QUANTITY_ON_HAND-RESERVED_QUANTITY)=0 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE;
SELECT 'TC-03-02' AS TEST_ID, 'All parts in ATP' AS TEST_NAME, 17 AS EXPECTED, COUNT(*) AS ACTUAL, CASE WHEN COUNT(*)=17 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE;
SELECT 'TC-03-03' AS TEST_ID, 'Valid risk values' AS TEST_NAME, 0 AS EXPECTED, COUNT_IF(PROCUREMENT_RISK NOT IN ('NO_RISK','ORDER_NOW','EXPEDITE','CRITICAL_SHORTAGE','UNKNOWN')) AS ACTUAL, CASE WHEN COUNT_IF(PROCUREMENT_RISK NOT IN ('NO_RISK','ORDER_NOW','EXPEDITE','CRITICAL_SHORTAGE','UNKNOWN'))=0 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.ANALYTICS.PROCUREMENT_RECOMMENDATIONS;
SELECT 'TC-03-07' AS TEST_ID, 'Suppliers active' AS TEST_NAME, 5 AS EXPECTED, COUNT(*) AS ACTUAL, CASE WHEN COUNT(*)=5 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.RAW_IT.SUPPLIERS WHERE ACTIVE=TRUE;
SELECT 'TC-03-08' AS TEST_ID, 'Part-supplier maps' AS TEST_NAME, 18 AS EXPECTED, COUNT(*) AS ACTUAL, CASE WHEN COUNT(*)=18 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS;
