-- ============================================================================
-- MFGPulse AI Test Suite: TC-04 Notifications
-- ============================================================================
SELECT 'TC-04-01' AS TEST_ID, 'Event types' AS TEST_NAME, 16 AS EXPECTED, COUNT(*) AS ACTUAL, CASE WHEN COUNT(*)=16 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS;
SELECT 'TC-04-02' AS TEST_ID, 'Personas configured' AS TEST_NAME, 0 AS EXPECTED, COUNT_IF(NOTIFY_PERSONAS IS NULL OR LENGTH(TRIM(NOTIFY_PERSONAS))=0) AS ACTUAL, CASE WHEN COUNT_IF(NOTIFY_PERSONAS IS NULL OR LENGTH(TRIM(NOTIFY_PERSONAS))=0)=0 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS;
SELECT 'TC-04-03' AS TEST_ID, 'In-app default ON' AS TEST_NAME, 16 AS EXPECTED, COUNT_IF(IN_APP_ENABLED=TRUE) AS ACTUAL, CASE WHEN COUNT_IF(IN_APP_ENABLED=TRUE)=16 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS;
