-- Truncate all MFGPULSE_DB tables and reload from MFGPULSE_DB_SHARED
-- Co-authored with CoCo

-- === ANALYTICS ===
TRUNCATE TABLE MFGPULSE_DB.ANALYTICS.ALERT_HISTORY;
INSERT INTO MFGPULSE_DB.ANALYTICS.ALERT_HISTORY SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.ALERT_HISTORY;

TRUNCATE TABLE MFGPULSE_DB.ANALYTICS.ASSET_COST_PROFILES;
INSERT INTO MFGPULSE_DB.ANALYTICS.ASSET_COST_PROFILES SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.ASSET_COST_PROFILES;

TRUNCATE TABLE MFGPULSE_DB.ANALYTICS.KPI_SNAPSHOTS;
INSERT INTO MFGPULSE_DB.ANALYTICS.KPI_SNAPSHOTS SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.KPI_SNAPSHOTS;

TRUNCATE TABLE MFGPULSE_DB.ANALYTICS.SHIFT_HANDOVER_HISTORY;
INSERT INTO MFGPULSE_DB.ANALYTICS.SHIFT_HANDOVER_HISTORY SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.SHIFT_HANDOVER_HISTORY;

-- === ML_MODELS ===
TRUNCATE TABLE MFGPULSE_DB.ML_MODELS.ANOMALY_SCORES;
INSERT INTO MFGPULSE_DB.ML_MODELS.ANOMALY_SCORES SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.ANOMALY_SCORES;

TRUNCATE TABLE MFGPULSE_DB.ML_MODELS.DRIFT_COMPARISON;
INSERT INTO MFGPULSE_DB.ML_MODELS.DRIFT_COMPARISON SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.DRIFT_COMPARISON;

TRUNCATE TABLE MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES;
INSERT INTO MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.FATIGUE_SCORES;

TRUNCATE TABLE MFGPULSE_DB.ML_MODELS.FEEDBACK_LOG;
INSERT INTO MFGPULSE_DB.ML_MODELS.FEEDBACK_LOG SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.FEEDBACK_LOG;

TRUNCATE TABLE MFGPULSE_DB.ML_MODELS.MODEL_REGISTRY;
INSERT INTO MFGPULSE_DB.ML_MODELS.MODEL_REGISTRY SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.MODEL_REGISTRY;

-- === PUBLIC ===
TRUNCATE TABLE MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG;
INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG SELECT * FROM MFGPULSE_DB_SHARED.PUBLIC.DEPLOYMENT_LOG;

-- === RAW_IT ===
TRUNCATE TABLE MFGPULSE_DB.RAW_IT.APP_NOTIFICATIONS;
-- Target has extra USERNAME_TARGET column not in share (defaults to NULL)
INSERT INTO MFGPULSE_DB.RAW_IT.APP_NOTIFICATIONS
    (NOTIF_ID, EVENT_TYPE, PERSONA_TARGET, TITLE, MESSAGE, ENTITY_ID, PRIORITY, IS_READ, DISMISSED, CREATED_AT)
SELECT NOTIF_ID, EVENT_TYPE, PERSONA_TARGET, TITLE, MESSAGE, ENTITY_ID, PRIORITY, IS_READ, DISMISSED, CREATED_AT
FROM MFGPULSE_DB_SHARED.RAW_IT.APP_NOTIFICATIONS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.FAILURE_MODE_BOM;
INSERT INTO MFGPULSE_DB.RAW_IT.FAILURE_MODE_BOM SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.FAILURE_MODE_BOM;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.INVENTORY_TRANSACTIONS;
INSERT INTO MFGPULSE_DB.RAW_IT.INVENTORY_TRANSACTIONS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.INVENTORY_TRANSACTIONS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.MAINTENANCE_LOGS;
INSERT INTO MFGPULSE_DB.RAW_IT.MAINTENANCE_LOGS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.MAINTENANCE_LOGS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS;
-- Target has extra UPDATED_AT/UPDATED_BY columns not in share (will use defaults)
INSERT INTO MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS
    (EVENT_TYPE, EVENT_LABEL, EMAIL_ENABLED, IN_APP_ENABLED, EMAIL_RECIPIENTS, NOTIFY_PERSONAS, PRIORITY)
SELECT EVENT_TYPE, EVENT_LABEL, EMAIL_ENABLED, IN_APP_ENABLED, EMAIL_RECIPIENTS, NOTIFY_PERSONAS, PRIORITY
FROM MFGPULSE_DB_SHARED.RAW_IT.NOTIFICATION_SETTINGS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PARTS_INVENTORY;
-- Share has extra MIN_STOCK/REORDER_POINT/REORDER_QTY columns not in target; select only matching columns
INSERT INTO MFGPULSE_DB.RAW_IT.PARTS_INVENTORY
    (PART_ID, PART_NAME, COMPATIBLE_ASSETS, QUANTITY_ON_HAND, LEAD_TIME_DAYS, UNIT_COST)
SELECT PART_ID, PART_NAME, COMPATIBLE_ASSETS, QUANTITY_ON_HAND, LEAD_TIME_DAYS, UNIT_COST
FROM MFGPULSE_DB_SHARED.RAW_IT.PARTS_INVENTORY;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PART_RESERVATIONS;
INSERT INTO MFGPULSE_DB.RAW_IT.PART_RESERVATIONS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PART_RESERVATIONS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PART_SUPPLIERS;
INSERT INTO MFGPULSE_DB.RAW_IT.PART_SUPPLIERS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PART_SUPPLIERS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PRODUCTION_OUTPUT;
INSERT INTO MFGPULSE_DB.RAW_IT.PRODUCTION_OUTPUT SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PRODUCTION_OUTPUT;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS;
INSERT INTO MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PURCHASE_ORDERS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES;
INSERT INTO MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PURCHASE_ORDER_LINES;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.SHIFT_SCHEDULE;
INSERT INTO MFGPULSE_DB.RAW_IT.SHIFT_SCHEDULE SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.SHIFT_SCHEDULE;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.SIMULATION_CONFIG;
-- CONFIG_ID is IDENTITY NOT NULL on target but nullable on share; column order also differs (CREATED_AT/CREATED_BY swapped)
INSERT INTO MFGPULSE_DB.RAW_IT.SIMULATION_CONFIG
    (ASSET_ID, SCENARIO, SEVERITY, HOURS, STATUS, ROWS_GENERATED, ESTIMATED_CREDITS, CREATED_AT, CREATED_BY, COMPLETED_AT)
SELECT ASSET_ID, SCENARIO, SEVERITY, HOURS, STATUS, ROWS_GENERATED, ESTIMATED_CREDITS, CREATED_AT, CREATED_BY, COMPLETED_AT
FROM MFGPULSE_DB_SHARED.RAW_IT.SIMULATION_CONFIG;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.SUPPLIERS;
INSERT INTO MFGPULSE_DB.RAW_IT.SUPPLIERS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.SUPPLIERS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.USERS;
INSERT INTO MFGPULSE_DB.RAW_IT.USERS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.USERS;

TRUNCATE TABLE MFGPULSE_DB.RAW_IT.WORK_ORDERS;
INSERT INTO MFGPULSE_DB.RAW_IT.WORK_ORDERS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.WORK_ORDERS;

-- === RAW_OT ===
TRUNCATE TABLE MFGPULSE_DB.RAW_OT.AMBIENT_CONDITIONS;
INSERT INTO MFGPULSE_DB.RAW_OT.AMBIENT_CONDITIONS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.AMBIENT_CONDITIONS;

TRUNCATE TABLE MFGPULSE_DB.RAW_OT.ASSET_MASTER;
INSERT INTO MFGPULSE_DB.RAW_OT.ASSET_MASTER SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.ASSET_MASTER;

TRUNCATE TABLE MFGPULSE_DB.RAW_OT.SENSOR_METADATA;
INSERT INTO MFGPULSE_DB.RAW_OT.SENSOR_METADATA SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.SENSOR_METADATA;

TRUNCATE TABLE MFGPULSE_DB.RAW_OT.SENSOR_READINGS;
INSERT INTO MFGPULSE_DB.RAW_OT.SENSOR_READINGS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.SENSOR_READINGS;
