-- ============================================================
-- EMERGENCY STOP: Suspend All Credit-Consuming Resources
-- ============================================================
-- Run as ACCOUNTADMIN to suspend every warehouse, compute pool,
-- task, and pipe in the account.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- 1. SUSPEND ALL WAREHOUSES
-- ============================================================
SELECT SYSTEM$CANCEL_ALL_QUERIES(CURRENT_SESSION());

BEGIN
  SHOW WAREHOUSES;
  LET c CURSOR FOR
    SELECT "name" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "state" != 'SUSPENDED';
  FOR rec IN c DO
    EXECUTE IMMEDIATE 'ALTER WAREHOUSE "' || rec."name" || '" SUSPEND';
  END FOR;
END;

-- ============================================================
-- 2. SUSPEND ALL USER TASKS (MFGPULSE_DB.ANALYTICS DAG)
-- ============================================================
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_REFRESH_FATIGUE     SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_REFRESH_DTS         SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_GENERATE_WOS        SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_GENERATE_POS        SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CONVERT_PPOS        SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_SNAPSHOT_KPIS       SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_ARCHIVE_ALERTS      SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CHECK_DRIFT         SUSPEND;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CHECK_FRESHNESS     SUSPEND;

-- ============================================================
-- 3. SUSPEND ALL COMPUTE POOLS
-- ============================================================
ALTER COMPUTE POOL IF EXISTS SYSTEM_COMPUTE_POOL_CPU STOP ALL;
ALTER COMPUTE POOL IF EXISTS SYSTEM_COMPUTE_POOL_CPU SUSPEND;
ALTER COMPUTE POOL IF EXISTS SYSTEM_COMPUTE_POOL_GPU STOP ALL;
ALTER COMPUTE POOL IF EXISTS SYSTEM_COMPUTE_POOL_GPU SUSPEND;

-- ============================================================
-- 4. DISABLE AUTO-RESUME ON WAREHOUSES (optional safety net)
-- ============================================================
-- Uncomment if you want to prevent warehouses from auto-starting:
-- ALTER WAREHOUSE COMPUTE_WH               SET AUTO_RESUME = FALSE;
-- ALTER WAREHOUSE MFGPULSE_AUTOMATION_WH    SET AUTO_RESUME = FALSE;
-- ALTER WAREHOUSE SNOWFLAKE_LEARNING_WH     SET AUTO_RESUME = FALSE;
-- ALTER WAREHOUSE SYSTEM$STREAMLIT_NOTEBOOK_WH SET AUTO_RESUME = FALSE;

-- ============================================================
-- 5. VERIFY EVERYTHING IS STOPPED
-- ============================================================
SHOW WAREHOUSES;
SHOW TASKS IN ACCOUNT;
SHOW COMPUTE POOLS;

-- RESUME
-- Child tasks must be resumed BEFORE the root task.
-- Resuming the root first causes: "root task is not suspended" error on children.
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG SUSPEND; 
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_REFRESH_FATIGUE     RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_REFRESH_DTS         RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_GENERATE_WOS        RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_GENERATE_POS        RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CONVERT_PPOS        RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_SNAPSHOT_KPIS       RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_ARCHIVE_ALERTS      RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CHECK_DRIFT         RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.DAG_CHECK_FRESHNESS     RESUME;
ALTER TASK IF EXISTS MFGPULSE_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG RESUME; -- root task last
-- Execute root task
EXECUTE TASK MFGPULSE_DB.ANALYTICS.
