-- ============================================================
-- Copy MFGPULSE_DB_SHARED (shared DB) → MFGPULSE_DB (local)
-- ============================================================

-- 1. Create the target database
CREATE DATABASE IF NOT EXISTS MFGPULSE_DB;

-- 2. Create schemas
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.ML_FEATURES;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.ML_MODELS;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.RAW_IT;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.RAW_OT;
CREATE SCHEMA IF NOT EXISTS MFGPULSE_DB.AGENT;

-- 3. Copy tables with data (CTAS)

-- === ANALYTICS ===
CREATE or REPLACE TABLE MFGPULSE_DB.ANALYTICS.ALERT_HISTORY AS SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.ALERT_HISTORY;
CREATE or REPLACE TABLE MFGPULSE_DB.ANALYTICS.ASSET_COST_PROFILES AS SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.ASSET_COST_PROFILES;
CREATE or REPLACE TABLE MFGPULSE_DB.ANALYTICS.KPI_SNAPSHOTS AS SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.KPI_SNAPSHOTS;
CREATE or REPLACE TABLE MFGPULSE_DB.ANALYTICS.SHIFT_HANDOVER_HISTORY AS SELECT * FROM MFGPULSE_DB_SHARED.ANALYTICS.SHIFT_HANDOVER_HISTORY;

-- === ML_MODELS ===
CREATE or REPLACE TABLE MFGPULSE_DB.ML_MODELS.ANOMALY_SCORES AS SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.ANOMALY_SCORES;
CREATE or REPLACE TABLE MFGPULSE_DB.ML_MODELS.DRIFT_COMPARISON AS SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.DRIFT_COMPARISON;
CREATE or REPLACE TABLE MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES AS SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.FATIGUE_SCORES;
CREATE or REPLACE TABLE MFGPULSE_DB.ML_MODELS.FEEDBACK_LOG AS SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.FEEDBACK_LOG;
CREATE or REPLACE TABLE MFGPULSE_DB.ML_MODELS.MODEL_REGISTRY AS SELECT * FROM MFGPULSE_DB_SHARED.ML_MODELS.MODEL_REGISTRY;

-- === PUBLIC ===
CREATE or REPLACE TABLE MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG AS SELECT * FROM MFGPULSE_DB_SHARED.PUBLIC.DEPLOYMENT_LOG;

-- === RAW_IT ===
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.APP_NOTIFICATIONS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.APP_NOTIFICATIONS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.FAILURE_MODE_BOM AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.FAILURE_MODE_BOM;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.INVENTORY_TRANSACTIONS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.INVENTORY_TRANSACTIONS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.MAINTENANCE_LOGS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.MAINTENANCE_LOGS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.NOTIFICATION_SETTINGS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PARTS_INVENTORY AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PARTS_INVENTORY;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PART_RESERVATIONS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PART_RESERVATIONS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PART_SUPPLIERS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PART_SUPPLIERS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PRODUCTION_OUTPUT AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PRODUCTION_OUTPUT;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PURCHASE_ORDERS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.PURCHASE_ORDER_LINES;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.SHIFT_SCHEDULE AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.SHIFT_SCHEDULE;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.SIMULATION_CONFIG AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.SIMULATION_CONFIG;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.SUPPLIERS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.SUPPLIERS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.USERS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.USERS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_IT.WORK_ORDERS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_IT.WORK_ORDERS;

-- === RAW_OT ===
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_OT.AMBIENT_CONDITIONS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.AMBIENT_CONDITIONS;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_OT.ASSET_MASTER AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.ASSET_MASTER;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_OT.SENSOR_METADATA AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.SENSOR_METADATA;
CREATE or REPLACE TABLE MFGPULSE_DB.RAW_OT.SENSOR_READINGS AS SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.SENSOR_READINGS;

-- 4. Grant access
GRANT ALL PRIVILEGES ON DATABASE MFGPULSE_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE MFGPULSE_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MFGPULSE_DB TO ROLE SYSADMIN;

-- 5. Verify row counts
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA != 'INFORMATION_SCHEMA'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

DROP API INTEGRATION "MFGPulse";
CREATE OR REPLACE API INTEGRATION "MFGPulse"
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/AbilashCLT')
  API_USER_AUTHENTICATION = (TYPE = SNOWFLAKE_GITHUB_APP)
  ENABLED = TRUE;

SHOW INTEGRATIONS LIKE '%MFGPulse%';