-- ============================================================================
-- MFGPulse AI: 02 Base Tables
-- 19 base tables across RAW_OT, RAW_IT, ML_MODELS, ANALYTICS
-- ============================================================================

USE DATABASE MFGPULSE_DB;

-- === RAW_OT (Operational Technology) ===

CREATE OR REPLACE TABLE RAW_OT.ASSET_MASTER (
    ASSET_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ASSET_NAME VARCHAR(100) NOT NULL,
    ASSET_TYPE VARCHAR(50) NOT NULL,
    LINE_ID VARCHAR(20) NOT NULL,
    INSTALL_DATE DATE,
    MANUFACTURER VARCHAR(100),
    MODEL_NUMBER VARCHAR(50),
    RATED_RPM FLOAT,
    RATED_TEMP_MAX FLOAT
);

CREATE OR REPLACE TABLE RAW_OT.SENSOR_METADATA (
    SENSOR_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    ASSET_ID VARCHAR(20) NOT NULL,
    SENSOR_TYPE VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(100),
    CALIBRATION_DATE DATE,
    SAMPLING_RATE_HZ FLOAT
);

CREATE OR REPLACE TABLE RAW_OT.SENSOR_READINGS (
    READING_ID NUMBER AUTOINCREMENT,
    ASSET_ID VARCHAR(20) NOT NULL,
    TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    VIBRATION_X FLOAT, VIBRATION_Y FLOAT, VIBRATION_Z FLOAT,
    TEMPERATURE FLOAT, RPM FLOAT, PRESSURE FLOAT,
    CURRENT_AMPS FLOAT, ACOUSTIC_DB FLOAT,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_OT.AMBIENT_CONDITIONS (
    READING_DATE DATE NOT NULL,
    AMBIENT_TEMP_C FLOAT, HUMIDITY_PCT FLOAT, BAROMETRIC_PRESSURE_HPA FLOAT
);

-- === RAW_IT (Information Technology) ===

CREATE OR REPLACE TABLE RAW_IT.WORK_ORDERS (
    WO_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ASSET_ID VARCHAR(20) NOT NULL,
    WO_TYPE VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ NOT NULL,
    COMPLETED_DATE TIMESTAMP_NTZ,
    PRIORITY VARCHAR(10), STATUS VARCHAR(20),
    ASSIGNED_TO VARCHAR(100),
    LABOR_HOURS FLOAT, PARTS_COST FLOAT, TOTAL_COST FLOAT,
    ROOT_CAUSE_CONFIRMED VARCHAR,
    PART_USED BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_IT.MAINTENANCE_LOGS (
    LOG_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    WO_ID VARCHAR(20), ASSET_ID VARCHAR(20) NOT NULL,
    TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TECHNICIAN VARCHAR(100), NOTES_TEXT VARCHAR(2000)
);

CREATE OR REPLACE TABLE RAW_IT.PRODUCTION_OUTPUT (
    RECORD_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ASSET_ID VARCHAR(20) NOT NULL, SHIFT_ID VARCHAR(20),
    TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    UNITS_PRODUCED INT, GOOD_UNITS INT, IDEAL_CYCLE_TIME_SEC FLOAT
);

CREATE OR REPLACE TABLE RAW_IT.SHIFT_SCHEDULE (
    SHIFT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    LINE_ID VARCHAR(20) NOT NULL,
    SHIFT_START TIMESTAMP_NTZ NOT NULL, SHIFT_END TIMESTAMP_NTZ NOT NULL,
    OPERATOR_NAME VARCHAR(100), PLANNED_PRODUCTION_TIME_MINS INT
);

CREATE OR REPLACE TABLE RAW_IT.PARTS_INVENTORY (
    PART_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    PART_NAME VARCHAR(200) NOT NULL,
    COMPATIBLE_ASSETS ARRAY,
    QUANTITY_ON_HAND INT, LEAD_TIME_DAYS INT, UNIT_COST FLOAT
);

CREATE OR REPLACE TABLE RAW_IT.USERS (
    USER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL, EMAIL VARCHAR(200),
    PERSONA VARCHAR(50) NOT NULL, ROLE VARCHAR(50),
    LINE_ID VARCHAR(20),
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- === Procurement tables ===

CREATE OR REPLACE TABLE RAW_IT.SUPPLIERS (
    SUPPLIER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(200) NOT NULL,
    CONTACT_EMAIL VARCHAR(200), PHONE VARCHAR(50),
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_IT.PART_SUPPLIERS (
    PART_ID VARCHAR(20) NOT NULL, SUPPLIER_ID VARCHAR(20) NOT NULL,
    SUPPLIER_PART_NUMBER VARCHAR(50),
    STANDARD_LEAD_TIME_DAYS INT DEFAULT 7, EXPEDITE_LEAD_TIME_DAYS INT DEFAULT 3,
    MIN_ORDER_QTY INT DEFAULT 1, UNIT_COST FLOAT,
    PREFERRED_SUPPLIER BOOLEAN DEFAULT FALSE
);

CREATE OR REPLACE TABLE RAW_IT.PART_RESERVATIONS (
    RESERVATION_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    PART_ID VARCHAR(20) NOT NULL, ASSET_ID VARCHAR(20) NOT NULL,
    WO_ID VARCHAR(50), QUANTITY_RESERVED INT DEFAULT 1,
    REQUIRED_BY_DATE DATE, STATUS VARCHAR(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_IT.PURCHASE_ORDERS (
    PO_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SUPPLIER_ID VARCHAR(20), CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REQUIRED_BY_DATE DATE, EXPECTED_ARRIVAL_DATE DATE,
    STATUS VARCHAR(30) DEFAULT 'draft', PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
    TOTAL_COST FLOAT, CREATED_BY VARCHAR(100) DEFAULT 'SYSTEM',
    SOURCE VARCHAR(30) DEFAULT 'prediction',
    REJECTION_REASON VARCHAR,
    REJECTED_BY VARCHAR,
    REJECTED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_IT.PURCHASE_ORDER_LINES (
    PO_LINE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    PO_ID VARCHAR(50) NOT NULL, PART_ID VARCHAR(20) NOT NULL,
    ASSET_ID VARCHAR(20), WO_ID VARCHAR(50),
    QUANTITY_ORDERED INT DEFAULT 1, UNIT_COST FLOAT, LINE_COST FLOAT,
    RUL_HOURS_AT_ORDER FLOAT, FAILURE_MODE_PRED VARCHAR(50),
    PROCUREMENT_RISK VARCHAR(30)
);

-- === ML_MODELS ===

CREATE OR REPLACE TABLE ML_MODELS.MODEL_REGISTRY (
    MODEL_NAME VARCHAR(100), MODEL_TYPE VARCHAR(100),
    TRAINING_DATA VARCHAR(200),
    PRECISION_SCORE FLOAT, RECALL_SCORE FLOAT, F1_SCORE FLOAT,
    TOP_FEATURES VARCHAR(500),
    TRAINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ML_MODELS.FATIGUE_SCORES (
    ASSET_ID VARCHAR(20), TIMESTAMP TIMESTAMP_NTZ,
    FATIGUE_SCORE FLOAT, FATIGUE_LEVEL VARCHAR(20)
);

CREATE OR REPLACE TABLE ML_MODELS.ANOMALY_SCORES (
    SERIES VARIANT, TS TIMESTAMP_NTZ,
    Y FLOAT, FORECAST FLOAT, LOWER_BOUND FLOAT, UPPER_BOUND FLOAT,
    IS_ANOMALY BOOLEAN, PERCENTILE FLOAT, DISTANCE FLOAT
);

-- === ANALYTICS ===

CREATE OR REPLACE TABLE ANALYTICS.SHIFT_HANDOVER_HISTORY (
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SUMMARY_TEXT TEXT, WOS_GENERATED INT,
    PLANT_OEE FLOAT, CRITICAL_ASSETS INT
);
