-- ============================================================================
-- MFGPulse AI: 14 Automation — Task DAG
-- All automation runs as a single DAG: MFGPULSE_AUTOMATION_DAG (root, 720 min)
-- Uses dedicated MFGPULSE_AUTOMATION_WH (XS, 60s auto-suspend)
-- Monitored by MFGPULSE_AUTOMATION_GUARD (50 credits/month)
-- ============================================================================

USE DATABASE MFGPULSE_DB;

-- ============================================================================
-- INFRASTRUCTURE: Dedicated automation warehouse + resource monitor
-- ============================================================================

CREATE WAREHOUSE IF NOT EXISTS MFGPULSE_AUTOMATION_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for MFGPulse AI tasks and dynamic table refreshes.';

CREATE OR REPLACE RESOURCE MONITOR MFGPULSE_AUTOMATION_GUARD
    WITH CREDIT_QUOTA = 50
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE MFGPULSE_AUTOMATION_WH SET RESOURCE_MONITOR = MFGPULSE_AUTOMATION_GUARD;

-- ============================================================================
-- PROCEDURES (called by DAG tasks)
-- ============================================================================

-- 1. SIMULATE_ALL_FEEDS_RANDOM — sensor + production data with persistent degradation
--    (Full DDL in sql/ddl_objects.sql and docs/full_ddl_export.sql)

-- 2. REFRESH_FATIGUE_SCORES — batch-update fatigue for all assets
CREATE OR REPLACE PROCEDURE ML_MODELS.REFRESH_FATIGUE_SCORES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
DECLARE
    v_count NUMBER DEFAULT 0;
BEGIN
    INSERT INTO MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES (ASSET_ID, TIMESTAMP, FATIGUE_SCORE, FATIGUE_LEVEL)
    SELECT
        rs.ASSET_ID, rs.TIMESTAMP,
        MFGPULSE_DB.ML_MODELS.COMPUTE_FATIGUE_SCORE(
            rs.VIB_CREST_FACTOR_6H, rs.VIB_COEFF_VAR_6H, rs.VIB_PEAK_TO_PEAK_6H,
            rs.VIB_RATE_OF_CHANGE_1H, rs.VIB_ACCELERATION_1H,
            COALESCE(pc.ENERGY_BALANCE_RATIO, 1.0), COALESCE(pc.STRESS_INDEX, 0.0),
            COALESCE(si.VIB_XY_CORRELATION_DAILY, 0.3), COALESCE(si.ACOUSTIC_VIB_RATIO, 25.0)
        ) AS FATIGUE_SCORE,
        CASE
            WHEN MFGPULSE_DB.ML_MODELS.COMPUTE_FATIGUE_SCORE(
                rs.VIB_CREST_FACTOR_6H, rs.VIB_COEFF_VAR_6H, rs.VIB_PEAK_TO_PEAK_6H,
                rs.VIB_RATE_OF_CHANGE_1H, rs.VIB_ACCELERATION_1H,
                COALESCE(pc.ENERGY_BALANCE_RATIO, 1.0), COALESCE(pc.STRESS_INDEX, 0.0),
                COALESCE(si.VIB_XY_CORRELATION_DAILY, 0.3), COALESCE(si.ACOUSTIC_VIB_RATIO, 25.0)
            ) > 0.7 THEN 'CRITICAL'
            WHEN MFGPULSE_DB.ML_MODELS.COMPUTE_FATIGUE_SCORE(
                rs.VIB_CREST_FACTOR_6H, rs.VIB_COEFF_VAR_6H, rs.VIB_PEAK_TO_PEAK_6H,
                rs.VIB_RATE_OF_CHANGE_1H, rs.VIB_ACCELERATION_1H,
                COALESCE(pc.ENERGY_BALANCE_RATIO, 1.0), COALESCE(pc.STRESS_INDEX, 0.0),
                COALESCE(si.VIB_XY_CORRELATION_DAILY, 0.3), COALESCE(si.ACOUSTIC_VIB_RATIO, 25.0)
            ) > 0.4 THEN 'HIGH'
            WHEN MFGPULSE_DB.ML_MODELS.COMPUTE_FATIGUE_SCORE(
                rs.VIB_CREST_FACTOR_6H, rs.VIB_COEFF_VAR_6H, rs.VIB_PEAK_TO_PEAK_6H,
                rs.VIB_RATE_OF_CHANGE_1H, rs.VIB_ACCELERATION_1H,
                COALESCE(pc.ENERGY_BALANCE_RATIO, 1.0), COALESCE(pc.STRESS_INDEX, 0.0),
                COALESCE(si.VIB_XY_CORRELATION_DAILY, 0.3), COALESCE(si.ACOUSTIC_VIB_RATIO, 25.0)
            ) > 0.2 THEN 'ACCUMULATING'
            ELSE 'HEALTHY'
        END AS FATIGUE_LEVEL
    FROM MFGPULSE_DB.ML_FEATURES.ROLLING_STATS rs
    LEFT JOIN MFGPULSE_DB.ML_FEATURES.PHYSICS_COMPOSITE pc
        ON rs.ASSET_ID = pc.ASSET_ID AND rs.TIMESTAMP = pc.TIMESTAMP
    LEFT JOIN MFGPULSE_DB.ML_FEATURES.SENSOR_INTERACTIONS si
        ON rs.ASSET_ID = si.ASSET_ID AND rs.TIMESTAMP = si.TIMESTAMP
    WHERE rs.TIMESTAMP > (SELECT COALESCE(MAX(TIMESTAMP), '2000-01-01') FROM MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES)
    QUALIFY ROW_NUMBER() OVER (PARTITION BY rs.ASSET_ID ORDER BY rs.TIMESTAMP DESC) <= 48;
    SELECT COUNT(*) INTO :v_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
    RETURN 'Fatigue scores refreshed: ' || :v_count || ' rows at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- 3. REFRESH_ALL_DTS — force immediate DT refresh in dependency order
CREATE OR REPLACE PROCEDURE ANALYTICS.REFRESH_ALL_DTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
BEGIN
    -- Layer 0: Raw → Curated
    ALTER DYNAMIC TABLE MFGPULSE_DB.CURATED.SENSOR_WITH_CONTEXT REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.CURATED.ASSET_HEALTH_CURRENT REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.CURATED.FAILURE_HISTORY REFRESH;
    -- Layer 1: Raw → Features
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.ROLLING_STATS REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.PHYSICS_COMPOSITE REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.SENSOR_INTERACTIONS REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.LABELED_DATA REFRESH;
    -- Layer 2: Features → Advanced features
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.TEMPORAL_MEMORY REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.FLEET_COMPARISON REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_FEATURES.CROSS_DOMAIN REFRESH;
    -- Layer 3: Features + Fatigue → Predictions
    ALTER DYNAMIC TABLE MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS REFRESH;
    -- Layer 4: Predictions → Business
    ALTER DYNAMIC TABLE MFGPULSE_DB.ANALYTICS.ACTIVE_ALERTS REFRESH;
    ALTER DYNAMIC TABLE MFGPULSE_DB.ANALYTICS.OEE_METRICS REFRESH;
    RETURN 'All 13 DTs refreshed at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- 4. AUTO_GENERATE_WORK_ORDERS — (full DDL in sql/ddl_objects.sql)
-- 5. AUTO_GENERATE_PURCHASE_ORDERS — (full DDL in sql/ddl_objects.sql)
-- 6. AUTO_CONVERT_PLANNED_POS — (full DDL in sql/ddl_objects.sql)

-- ============================================================================
-- TASK DAG: MFGPULSE_AUTOMATION_DAG
-- Chain: Simulate → Fatigue → DT Refresh → WO Gen → PO Gen → PPO Convert
-- ============================================================================

-- Root task: runs every 12 hours, generates sensor + production data
CREATE OR REPLACE TASK ANALYTICS.MFGPULSE_AUTOMATION_DAG
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    SCHEDULE = '720 MINUTE'
    SUSPEND_TASK_AFTER_NUM_FAILURES = 2
AS
    CALL MFGPULSE_DB.RAW_OT.SIMULATE_ALL_FEEDS_RANDOM();

-- Child 1: Refresh fatigue scores after new sensor data
CREATE OR REPLACE TASK ANALYTICS.DAG_REFRESH_FATIGUE
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    AFTER ANALYTICS.MFGPULSE_AUTOMATION_DAG
AS
    CALL MFGPULSE_DB.ML_MODELS.REFRESH_FATIGUE_SCORES();

-- Child 2: Force DT refresh cascade (with fresh fatigue data)
CREATE OR REPLACE TASK ANALYTICS.DAG_REFRESH_DTS
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    AFTER ANALYTICS.DAG_REFRESH_FATIGUE
AS
    CALL MFGPULSE_DB.ANALYTICS.REFRESH_ALL_DTS();

-- Child 3: Auto-generate work orders (using fresh predictions)
CREATE OR REPLACE TASK ANALYTICS.DAG_GENERATE_WOS
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    AFTER ANALYTICS.DAG_REFRESH_DTS
AS
    CALL MFGPULSE_DB.ANALYTICS.AUTO_GENERATE_WORK_ORDERS();

-- Child 4: Auto-generate purchase orders (for new WOs)
CREATE OR REPLACE TASK ANALYTICS.DAG_GENERATE_POS
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    AFTER ANALYTICS.DAG_GENERATE_WOS
AS
    CALL MFGPULSE_DB.ANALYTICS.AUTO_GENERATE_PURCHASE_ORDERS();

-- Child 5: Auto-convert planned POs to actual POs
CREATE OR REPLACE TASK ANALYTICS.DAG_CONVERT_PPOS
    WAREHOUSE = MFGPULSE_AUTOMATION_WH
    AFTER ANALYTICS.DAG_GENERATE_POS
AS
    CALL MFGPULSE_DB.ANALYTICS.AUTO_CONVERT_PLANNED_POS();

-- ============================================================================
-- STARTUP: Resume children first (bottom-up), then root last
-- ============================================================================
-- ALTER TASK ANALYTICS.DAG_CONVERT_PPOS RESUME;
-- ALTER TASK ANALYTICS.DAG_GENERATE_POS RESUME;
-- ALTER TASK ANALYTICS.DAG_GENERATE_WOS RESUME;
-- ALTER TASK ANALYTICS.DAG_REFRESH_DTS RESUME;
-- ALTER TASK ANALYTICS.DAG_REFRESH_FATIGUE RESUME;
-- ALTER TASK ANALYTICS.MFGPULSE_AUTOMATION_DAG RESUME;

-- ============================================================================
-- LEGACY TASKS (deprecated — replaced by DAG above)
-- ============================================================================
-- SIMULATE_ALL_FEEDS, SIMULATE_SENSOR_FEED, SIMULATE_PRODUCTION,
-- AUTO_PROCUREMENT_REVIEW, AUTO_CONVERT_PLANNED_POS_TASK,
-- AUTO_GENERATE_WORK_ORDERS_TASK
-- All suspended. Use the DAG for synchronized automation.
