-- ============================================================================
-- MFGPulse AI: 16 Procurement Views
-- 5 views: PARTS_AVAILABLE_TO_PROMISE, PROCUREMENT_RECOMMENDATIONS,
--          PARTS_LIFECYCLE_INSIGHTS, PROCUREMENT_PERFORMANCE, SUPPLIER_SCORECARD
-- ============================================================================
-- Dependencies: PARTS_INVENTORY, PART_RESERVATIONS, PART_SUPPLIERS, SUPPLIERS,
--   PURCHASE_ORDERS, PURCHASE_ORDER_LINES, WORK_ORDERS, LIVE_PREDICTIONS
-- Run AFTER: scripts 01-12 (all base tables, DTs, and LIVE_PREDICTIONS must exist)
-- ============================================================================

USE DATABASE MFGPULSE_DB;


-- ============================================================================
-- 1. PARTS_AVAILABLE_TO_PROMISE — ATP calculation per part
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.PARTS_AVAILABLE_TO_PROMISE AS
SELECT
    pi.PART_ID,
    pi.PART_NAME,
    pi.QUANTITY_ON_HAND,
    COALESCE(r.RESERVED_QUANTITY, 0) AS RESERVED_QUANTITY,
    GREATEST(0, pi.QUANTITY_ON_HAND - COALESCE(r.RESERVED_QUANTITY, 0)) AS AVAILABLE_TO_PROMISE,
    pi.LEAD_TIME_DAYS,
    pi.UNIT_COST,
    COALESCE(ps.SUPPLIER_NAME, 'No Supplier') AS SUPPLIER_NAME,
    COALESCE(po_incoming.INCOMING_QTY, 0) AS INCOMING_PO_QTY
FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
LEFT JOIN (
    SELECT PART_ID, SUM(QUANTITY_RESERVED) AS RESERVED_QUANTITY
    FROM MFGPULSE_DB.RAW_IT.PART_RESERVATIONS
    WHERE STATUS = 'active'
    GROUP BY PART_ID
) r ON pi.PART_ID = r.PART_ID
LEFT JOIN (
    SELECT ps2.PART_ID, s.SUPPLIER_NAME
    FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2
    JOIN MFGPULSE_DB.RAW_IT.SUPPLIERS s ON ps2.SUPPLIER_ID = s.SUPPLIER_ID
    WHERE ps2.PREFERRED_SUPPLIER = TRUE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
) ps ON pi.PART_ID = ps.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, SUM(pol.QUANTITY_ORDERED) AS INCOMING_QTY
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS IN ('approved','ordered','shipped')
    GROUP BY pol.PART_ID
) po_incoming ON pi.PART_ID = po_incoming.PART_ID;


-- ============================================================================
-- 2. PROCUREMENT_RECOMMENDATIONS — Industry-standard 3-signal evaluation
--    Signal 1: Urgency (RUL-based)
--    Signal 2: Supply (ATP, reservations, competing demand)
--    Signal 3: Fulfillment (lead time vs RUL gap)
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.PROCUREMENT_RECOMMENDATIONS AS
WITH asset_predictions AS (
    SELECT lp.ASSET_ID, lp.ASSET_NAME, lp.FAILURE_MODE_PRED, lp.RUL_HOURS,
        lp.STAGE_PRED, lp.DEGRADATION_SCORE, lp.FATIGUE_SCORE
    FROM MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp
    WHERE lp.FAILURE_MODE_PRED != 'normal' OR lp.STAGE_PRED IN ('Warning','Critical')
),
compatible_parts AS (
    SELECT DISTINCT
        ap.ASSET_ID, ap.ASSET_NAME, ap.FAILURE_MODE_PRED, ap.RUL_HOURS,
        ap.STAGE_PRED, ap.DEGRADATION_SCORE, ap.FATIGUE_SCORE,
        pi.PART_ID, pi.PART_NAME, pi.UNIT_COST, pi.LEAD_TIME_DAYS
    FROM asset_predictions ap
    JOIN MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
      ON ARRAY_CONTAINS(ap.ASSET_ID::VARIANT, pi.COMPATIBLE_ASSETS)
),
competing_assets AS (
    SELECT pi2.PART_ID, COUNT(DISTINCT lp2.ASSET_ID) AS COMPETING_ASSETS
    FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi2
    JOIN MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp2
      ON ARRAY_CONTAINS(lp2.ASSET_ID::VARIANT, pi2.COMPATIBLE_ASSETS)
    WHERE lp2.FAILURE_MODE_PRED != 'normal' OR lp2.STAGE_PRED IN ('Warning','Critical')
    GROUP BY pi2.PART_ID
),
active_reservations AS (
    SELECT PART_ID, ASSET_ID, WO_ID, SUM(QUANTITY_RESERVED) AS RESERVED_QTY
    FROM MFGPULSE_DB.RAW_IT.PART_RESERVATIONS
    WHERE STATUS = 'active'
    GROUP BY PART_ID, ASSET_ID, WO_ID
),
earliest_arrivals AS (
    SELECT pol.PART_ID, MIN(po.EXPECTED_ARRIVAL_DATE) AS EARLIEST_PO_ARRIVAL
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS NOT IN ('cancelled','received')
    GROUP BY pol.PART_ID
),
with_supply AS (
    SELECT cp.*,
        atp.AVAILABLE_TO_PROMISE,
        atp.INCOMING_PO_QTY,
        COALESCE(atp.SUPPLIER_NAME, 'Unknown') AS SUPPLIER_NAME,
        COALESCE(ps.SUPPLIER_ID, 'SUP-001') AS SUPPLIER_ID,
        1 AS REQUIRED_QUANTITY,
        -- Effective ATP: adjust for competing demand from other at-risk assets
        GREATEST(0, COALESCE(atp.AVAILABLE_TO_PROMISE, 0)
            - GREATEST(0, COALESCE(ca.COMPETING_ASSETS, 1) - 1)) AS EFFECTIVE_ATP,
        COALESCE(atp.AVAILABLE_TO_PROMISE, 0) + COALESCE(atp.INCOMING_PO_QTY, 0) - 1 AS NET_POSITION,
        DATEADD('hour', GREATEST(cp.RUL_HOURS - 24, 0), CURRENT_TIMESTAMP())::DATE AS REQUIRED_BY_DATE,
        -- Lead time feasibility: can we get parts before predicted failure?
        CASE WHEN cp.LEAD_TIME_DAYS * 24 <= cp.RUL_HOURS THEN TRUE ELSE FALSE END AS LEAD_TIME_FEASIBLE,
        epo.OPEN_PO_ID,
        wo.WO_ID,
        COALESCE(ca.COMPETING_ASSETS, 1) AS COMPETING_ASSETS,
        ea.EARLIEST_PO_ARRIVAL,
        -- Reservation check
        CASE WHEN ar.RESERVED_QTY > 0 THEN TRUE ELSE FALSE END AS HAS_ACTIVE_RESERVATION,
        COALESCE(ar.RESERVED_QTY, 0) AS RESERVED_QTY
    FROM compatible_parts cp
    LEFT JOIN MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE atp ON cp.PART_ID = atp.PART_ID
    LEFT JOIN (
        SELECT ps2.PART_ID, ps2.SUPPLIER_ID
        FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2 WHERE ps2.PREFERRED_SUPPLIER = TRUE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
    ) ps ON cp.PART_ID = ps.PART_ID
    LEFT JOIN (
        SELECT pol.PART_ID, pol.ASSET_ID, po.PO_ID AS OPEN_PO_ID
        FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
        JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
        WHERE po.STATUS NOT IN ('cancelled','received')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY pol.PART_ID, pol.ASSET_ID ORDER BY po.CREATED_DATE DESC) = 1
    ) epo ON cp.PART_ID = epo.PART_ID AND cp.ASSET_ID = epo.ASSET_ID
    LEFT JOIN (
        SELECT ASSET_ID, WO_ID FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS
        WHERE STATUS IN ('open','in_progress')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY CREATED_DATE DESC) = 1
    ) wo ON cp.ASSET_ID = wo.ASSET_ID
    LEFT JOIN competing_assets ca ON cp.PART_ID = ca.PART_ID
    LEFT JOIN earliest_arrivals ea ON cp.PART_ID = ea.PART_ID
    LEFT JOIN active_reservations ar ON cp.PART_ID = ar.PART_ID AND cp.ASSET_ID = ar.ASSET_ID
)
SELECT
    ws.ASSET_ID, ws.ASSET_NAME, ws.PART_ID, ws.PART_NAME,
    ws.SUPPLIER_ID, ws.SUPPLIER_NAME,
    ws.RUL_HOURS, ws.STAGE_PRED, ws.FAILURE_MODE_PRED,
    ws.DEGRADATION_SCORE, ws.FATIGUE_SCORE,
    -- PROCUREMENT_RISK: 3-signal evaluation (urgency + supply + fulfillment)
    CASE
        WHEN ws.HAS_ACTIVE_RESERVATION                                         THEN 'RESERVED'
        WHEN ws.AVAILABLE_TO_PROMISE <= 0 AND ws.INCOMING_PO_QTY <= 0          THEN 'CRITICAL_SHORTAGE'
        WHEN ws.RUL_HOURS < 72  AND ws.EFFECTIVE_ATP < ws.REQUIRED_QUANTITY
             AND NOT ws.LEAD_TIME_FEASIBLE                                      THEN 'EXPEDITE'
        WHEN ws.RUL_HOURS < 72  AND ws.EFFECTIVE_ATP < ws.REQUIRED_QUANTITY    THEN 'EXPEDITE'
        WHEN ws.RUL_HOURS < 72  AND ws.EFFECTIVE_ATP >= ws.REQUIRED_QUANTITY   THEN 'NO_RISK'
        WHEN ws.NET_POSITION < 0                                                THEN 'ORDER_NOW'
        WHEN ws.RUL_HOURS < 336 AND ws.EFFECTIVE_ATP < ws.REQUIRED_QUANTITY
             AND NOT ws.LEAD_TIME_FEASIBLE                                      THEN 'EXPEDITE'
        WHEN ws.RUL_HOURS < 336 AND ws.EFFECTIVE_ATP < ws.REQUIRED_QUANTITY    THEN 'ORDER_NOW'
        WHEN ws.RUL_HOURS < 336 AND ws.EFFECTIVE_ATP >= ws.REQUIRED_QUANTITY   THEN 'NO_RISK'
        ELSE 'NO_RISK'
    END AS PROCUREMENT_RISK,
    -- RECOMMENDED_PROCUREMENT_ACTION: what to do
    CASE
        WHEN ws.HAS_ACTIVE_RESERVATION                                         THEN 'MONITOR_RESERVATION'
        WHEN ws.OPEN_PO_ID IS NOT NULL                                          THEN 'MONITOR_EXISTING_PO'
        WHEN ws.AVAILABLE_TO_PROMISE <= 0 AND ws.INCOMING_PO_QTY <= 0          THEN 'ESCALATE_CRITICAL_SHORTAGE'
        WHEN ws.RUL_HOURS < 72  AND ws.EFFECTIVE_ATP >= ws.REQUIRED_QUANTITY   THEN 'RESERVE_STOCK'
        WHEN ws.RUL_HOURS < 72  AND NOT ws.LEAD_TIME_FEASIBLE                 THEN 'ESCALATE_CRITICAL_SHORTAGE'
        WHEN ws.RUL_HOURS < 72                                                  THEN 'EXPEDITE_PO'
        WHEN ws.EFFECTIVE_ATP >= ws.REQUIRED_QUANTITY AND ws.RUL_HOURS < 336   THEN 'RESERVE_STOCK'
        WHEN ws.NET_POSITION < 0                                                THEN 'CREATE_PO'
        WHEN ws.RUL_HOURS < 336 AND NOT ws.LEAD_TIME_FEASIBLE                 THEN 'EXPEDITE_PO'
        WHEN ws.RUL_HOURS < 336                                                 THEN 'CREATE_PO'
        ELSE 'NO_ACTION'
    END AS RECOMMENDED_PROCUREMENT_ACTION,
    ws.OPEN_PO_ID, ws.WO_ID,
    ws.AVAILABLE_TO_PROMISE, ws.EFFECTIVE_ATP, ws.INCOMING_PO_QTY, ws.NET_POSITION,
    ws.REQUIRED_QUANTITY, ws.REQUIRED_BY_DATE,
    ws.LEAD_TIME_DAYS, ws.UNIT_COST,
    ws.COMPETING_ASSETS,
    ws.HAS_ACTIVE_RESERVATION, ws.RESERVED_QTY,
    ws.LEAD_TIME_FEASIBLE,
    CASE
        WHEN ws.NET_POSITION >= 2 THEN 'SURPLUS'
        WHEN ws.NET_POSITION >= 0 THEN 'TIGHT'
        ELSE 'DEFICIT'
    END AS BUFFER_STATUS,
    ws.LEAD_TIME_DAYS - CEIL(ws.RUL_HOURS / 24.0) AS LEAD_TIME_GAP_DAYS,
    ws.EARLIEST_PO_ARRIVAL
FROM with_supply ws;


-- ============================================================================
-- 3. PARTS_LIFECYCLE_INSIGHTS — part health, usage trends, procurement history
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.PARTS_LIFECYCLE_INSIGHTS AS
SELECT
    pi.PART_ID, pi.PART_NAME, pi.QUANTITY_ON_HAND, pi.UNIT_COST, pi.LEAD_TIME_DAYS,
    COALESCE(wo_usage.TIMES_USED, 0) AS TIMES_USED_IN_WOS,
    COALESCE(wo_usage.TOTAL_WO_COST, 0) AS TOTAL_WO_COST_INVOLVING_PART,
    COALESCE(po_history.TOTAL_ORDERED, 0) AS TOTAL_ORDERED_HISTORICALLY,
    COALESCE(po_history.LAST_ORDERED_DATE, NULL) AS LAST_ORDERED_DATE,
    COALESCE(res.ACTIVE_RESERVATIONS, 0) AS ACTIVE_RESERVATIONS,
    COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND) AS AVAILABLE_TO_PROMISE,
    CASE
        WHEN pi.QUANTITY_ON_HAND = 0 THEN 'OUT_OF_STOCK'
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND) <= 1 THEN 'LOW_STOCK'
        WHEN pi.LEAD_TIME_DAYS > 14 THEN 'LONG_LEAD_TIME'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS,
    ARRAY_SIZE(pi.COMPATIBLE_ASSETS) AS COMPATIBLE_ASSET_COUNT,
    ps.SUPPLIER_NAME AS PREFERRED_SUPPLIER,
    COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) AS AT_RISK_ASSET_COUNT,
    COALESCE(at_risk.AT_RISK_ASSETS, '') AS AT_RISK_ASSETS,
    COALESCE(atp.INCOMING_PO_QTY, 0) AS INCOMING_QTY,
    COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
        + COALESCE(atp.INCOMING_PO_QTY, 0)
        - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) AS NET_POSITION,
    CASE
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
             + COALESCE(atp.INCOMING_PO_QTY, 0)
             - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) >= 2 THEN 'SURPLUS'
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
             + COALESCE(atp.INCOMING_PO_QTY, 0)
             - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) >= 0 THEN 'TIGHT'
        ELSE 'DEFICIT'
    END AS BUFFER_STATUS,
    CASE
        WHEN COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) = 0 THEN NULL
        ELSE ROUND(COALESCE(at_risk.MIN_RUL_HOURS, 0) / 24.0, 1)
    END AS EST_DAYS_UNTIL_STOCKOUT,
    ROUND(COALESCE(at_risk.MIN_RUL_HOURS, 0) / 24.0, 1) AS MIN_RUL_DAYS,
    po_arrival.EARLIEST_ARRIVAL
FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
LEFT JOIN (
    SELECT pol.PART_ID, COUNT(DISTINCT wo.WO_ID) AS TIMES_USED, SUM(wo.TOTAL_COST) AS TOTAL_WO_COST
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.WORK_ORDERS wo ON pol.WO_ID = wo.WO_ID
    GROUP BY pol.PART_ID
) wo_usage ON pi.PART_ID = wo_usage.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, SUM(pol.QUANTITY_ORDERED) AS TOTAL_ORDERED, MAX(po.CREATED_DATE) AS LAST_ORDERED_DATE
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    GROUP BY pol.PART_ID
) po_history ON pi.PART_ID = po_history.PART_ID
LEFT JOIN (
    SELECT PART_ID, COUNT(*) AS ACTIVE_RESERVATIONS
    FROM MFGPULSE_DB.RAW_IT.PART_RESERVATIONS WHERE STATUS = 'active'
    GROUP BY PART_ID
) res ON pi.PART_ID = res.PART_ID
LEFT JOIN MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE atp ON pi.PART_ID = atp.PART_ID
LEFT JOIN (
    SELECT ps2.PART_ID, s.SUPPLIER_NAME
    FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2
    JOIN MFGPULSE_DB.RAW_IT.SUPPLIERS s ON ps2.SUPPLIER_ID = s.SUPPLIER_ID
    WHERE ps2.PREFERRED_SUPPLIER = TRUE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
) ps ON pi.PART_ID = ps.PART_ID
LEFT JOIN (
    SELECT pi2.PART_ID,
        COUNT(DISTINCT lp.ASSET_ID) AS AT_RISK_ASSET_COUNT,
        LISTAGG(DISTINCT lp.ASSET_NAME, ', ') WITHIN GROUP (ORDER BY lp.ASSET_NAME) AS AT_RISK_ASSETS,
        MIN(lp.RUL_HOURS) AS MIN_RUL_HOURS
    FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi2
    JOIN MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp
      ON ARRAY_CONTAINS(lp.ASSET_ID::VARIANT, pi2.COMPATIBLE_ASSETS)
    WHERE lp.FAILURE_MODE_PRED != 'normal' OR lp.STAGE_PRED IN ('Warning','Critical')
    GROUP BY pi2.PART_ID
) at_risk ON pi.PART_ID = at_risk.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, MIN(po.EXPECTED_ARRIVAL_DATE) AS EARLIEST_ARRIVAL
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS NOT IN ('cancelled','received')
    GROUP BY pol.PART_ID
) po_arrival ON pi.PART_ID = po_arrival.PART_ID;


-- ============================================================================
-- 4. PROCUREMENT_PERFORMANCE — Cross-entity metrics (Tier 2)
--    Links: WO → PO → Parts → Predictions
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.PROCUREMENT_PERFORMANCE AS
WITH wo_po_link AS (
    SELECT
        wo.WO_ID, wo.ASSET_ID, wo.WO_TYPE, wo.CREATED_DATE AS WO_CREATED,
        wo.COMPLETED_DATE AS WO_COMPLETED, wo.STATUS AS WO_STATUS,
        wo.ROOT_CAUSE_CONFIRMED, wo.PART_USED,
        wo.TOTAL_COST AS WO_COST,
        pol.PO_ID, pol.PART_ID, pol.FAILURE_MODE_PRED AS PRED_AT_ORDER,
        po.CREATED_DATE AS PO_CREATED, po.STATUS AS PO_STATUS,
        po.EXPECTED_ARRIVAL_DATE,
        am.ASSET_NAME, am.ASSET_TYPE
    FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS wo
    JOIN MFGPULSE_DB.RAW_OT.ASSET_MASTER am ON wo.ASSET_ID = am.ASSET_ID
    LEFT JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol ON wo.WO_ID = pol.WO_ID
    LEFT JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
),
-- WO-to-PO response time
wo_po_lag AS (
    SELECT
        WO_ID, ASSET_ID, ASSET_NAME,
        WO_CREATED, PO_CREATED,
        DATEDIFF('hour', WO_CREATED, PO_CREATED) AS WO_TO_PO_LAG_HOURS
    FROM wo_po_link
    WHERE PO_CREATED IS NOT NULL
),
-- WO blocked time (open but not started due to parts)
wo_blocked AS (
    SELECT
        wo.WO_ID, wo.ASSET_ID,
        wo.CREATED_DATE AS WO_CREATED,
        MIN(n.CREATED_AT) AS FIRST_START,
        DATEDIFF('hour', wo.CREATED_DATE, MIN(n.CREATED_AT)) AS WO_BLOCKED_HOURS
    FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS wo
    LEFT JOIN MFGPULSE_DB.RAW_IT.APP_NOTIFICATIONS n
        ON n.WO_ID = wo.WO_ID AND n.EVENT_TYPE = 'WO_STARTED'
    WHERE wo.STATUS IN ('in_progress', 'completed')
    GROUP BY wo.WO_ID, wo.ASSET_ID, wo.CREATED_DATE
),
-- Repeat failures: same asset + failure mode within 60 days
repeat_failures AS (
    SELECT
        w1.WO_ID,
        w1.ASSET_ID,
        w1.ROOT_CAUSE_CONFIRMED AS FAILURE_MODE,
        COUNT(w2.WO_ID) AS REPEAT_COUNT
    FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS w1
    JOIN MFGPULSE_DB.RAW_IT.WORK_ORDERS w2
        ON w1.ASSET_ID = w2.ASSET_ID
        AND w1.ROOT_CAUSE_CONFIRMED = w2.ROOT_CAUSE_CONFIRMED
        AND w2.CREATED_DATE > w1.COMPLETED_DATE
        AND w2.CREATED_DATE <= DATEADD('day', 60, w1.COMPLETED_DATE)
        AND w1.WO_ID != w2.WO_ID
    WHERE w1.STATUS = 'completed' AND w1.ROOT_CAUSE_CONFIRMED IS NOT NULL
    GROUP BY w1.WO_ID, w1.ASSET_ID, w1.ROOT_CAUSE_CONFIRMED
),
-- Cost avoidance: emergency vs preventive/corrective cost differential
cost_avoidance AS (
    SELECT
        wo.WO_ID, wo.ASSET_ID, wo.WO_TYPE,
        wo.TOTAL_COST,
        CASE
            WHEN wo.WO_TYPE IN ('preventive', 'corrective') THEN
                (SELECT AVG(w2.TOTAL_COST) FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS w2
                 WHERE w2.WO_TYPE = 'emergency' AND w2.ASSET_ID = wo.ASSET_ID AND w2.TOTAL_COST IS NOT NULL)
                - wo.TOTAL_COST
            ELSE 0
        END AS COST_AVOIDED
    FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS wo
    WHERE wo.STATUS = 'completed' AND wo.TOTAL_COST IS NOT NULL
)
SELECT
    wpl.WO_ID, wpl.ASSET_ID, wpl.ASSET_NAME, wpl.ASSET_TYPE,
    wpl.WO_TYPE, wpl.WO_STATUS, wpl.WO_CREATED, wpl.WO_COMPLETED,
    wpl.ROOT_CAUSE_CONFIRMED, wpl.PART_USED, wpl.WO_COST,
    wpl.PO_ID, wpl.PART_ID, wpl.PO_STATUS,
    COALESCE(wpl2.WO_TO_PO_LAG_HOURS, NULL) AS WO_TO_PO_LAG_HOURS,
    COALESCE(wb.WO_BLOCKED_HOURS, 0) AS WO_BLOCKED_HOURS,
    COALESCE(rf.REPEAT_COUNT, 0) AS REPEAT_FAILURE_COUNT,
    rf.FAILURE_MODE AS REPEAT_FAILURE_MODE,
    COALESCE(ca.COST_AVOIDED, 0) AS COST_AVOIDED,
    CASE WHEN wpl.WO_TYPE IN ('preventive','corrective') AND wpl.ROOT_CAUSE_CONFIRMED IS NOT NULL
         THEN TRUE ELSE FALSE END AS PREDICTION_LED_TO_WO,
    CASE WHEN wpl.PART_USED = TRUE AND wpl.WO_TYPE IN ('preventive','corrective')
         THEN 'CONSUMED_AS_PREDICTED'
         WHEN wpl.PART_USED = FALSE AND wpl.WO_TYPE IN ('preventive','corrective')
         THEN 'NOT_CONSUMED'
         ELSE 'N/A'
    END AS PART_CONSUMPTION_OUTCOME
FROM wo_po_link wpl
LEFT JOIN wo_po_lag wpl2 ON wpl.WO_ID = wpl2.WO_ID
LEFT JOIN wo_blocked wb ON wpl.WO_ID = wb.WO_ID
LEFT JOIN repeat_failures rf ON wpl.WO_ID = rf.WO_ID
LEFT JOIN cost_avoidance ca ON wpl.WO_ID = ca.WO_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY wpl.WO_ID ORDER BY wpl.PO_CREATED DESC NULLS LAST) = 1;


-- ============================================================================
-- 5. SUPPLIER_SCORECARD — Supplier performance metrics (Tier 3)
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.SUPPLIER_SCORECARD AS
WITH po_delivery AS (
    SELECT
        po.PO_ID, po.SUPPLIER_ID, po.STATUS,
        po.CREATED_DATE, po.EXPECTED_ARRIVAL_DATE,
        po.PRIORITY,
        pol.PART_ID, pol.UNIT_COST AS LINE_UNIT_COST,
        ps.UNIT_COST AS CATALOG_UNIT_COST,
        ps.STANDARD_LEAD_TIME_DAYS,
        ps.EXPEDITE_LEAD_TIME_DAYS,
        CASE WHEN po.STATUS = 'received' THEN TRUE ELSE FALSE END AS IS_DELIVERED,
        CASE WHEN po.PRIORITY IN ('EMERGENCY','HIGH') THEN TRUE ELSE FALSE END AS IS_EXPEDITED
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol ON po.PO_ID = pol.PO_ID
    LEFT JOIN MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps
        ON pol.PART_ID = ps.PART_ID AND po.SUPPLIER_ID = ps.SUPPLIER_ID
    WHERE po.STATUS NOT IN ('draft','cancelled')
)
SELECT
    s.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    s.CONTACT_EMAIL,
    COUNT(DISTINCT pd.PO_ID) AS TOTAL_POS,
    COUNT(DISTINCT CASE WHEN pd.IS_DELIVERED THEN pd.PO_ID END) AS DELIVERED_POS,
    COUNT(DISTINCT CASE WHEN pd.IS_EXPEDITED THEN pd.PO_ID END) AS EXPEDITED_POS,
    -- On-time delivery rate (received POs where delivery <= expected)
    ROUND(DIV0NULL(
        COUNT(DISTINCT CASE WHEN pd.IS_DELIVERED THEN pd.PO_ID END),
        NULLIF(COUNT(DISTINCT pd.PO_ID), 0)
    ) * 100, 1) AS DELIVERY_RATE_PCT,
    -- Average lead time (days from PO creation to expected arrival)
    ROUND(AVG(DATEDIFF('day', pd.CREATED_DATE, pd.EXPECTED_ARRIVAL_DATE)), 1) AS AVG_LEAD_TIME_DAYS,
    -- Cost variance: actual line cost vs catalog cost
    ROUND(AVG(CASE WHEN pd.CATALOG_UNIT_COST > 0
        THEN (pd.LINE_UNIT_COST - pd.CATALOG_UNIT_COST) / pd.CATALOG_UNIT_COST * 100
        ELSE 0 END), 1) AS AVG_COST_VARIANCE_PCT,
    -- Total spend
    SUM(pd.LINE_UNIT_COST) AS TOTAL_SPEND,
    -- Unique parts supplied
    COUNT(DISTINCT pd.PART_ID) AS UNIQUE_PARTS_SUPPLIED,
    -- Rejection rate
    ROUND(DIV0NULL(
        COUNT(DISTINCT CASE WHEN po_rej.PO_ID IS NOT NULL THEN po_rej.PO_ID END),
        NULLIF(COUNT(DISTINCT pd.PO_ID), 0)
    ) * 100, 1) AS REJECTION_RATE_PCT,
    -- Overall score (simple weighted: delivery 40%, cost 30%, reliability 30%)
    ROUND(
        (DIV0NULL(COUNT(DISTINCT CASE WHEN pd.IS_DELIVERED THEN pd.PO_ID END),
            NULLIF(COUNT(DISTINCT pd.PO_ID), 0)) * 40) +
        (GREATEST(0, 30 - ABS(AVG(CASE WHEN pd.CATALOG_UNIT_COST > 0
            THEN (pd.LINE_UNIT_COST - pd.CATALOG_UNIT_COST) / pd.CATALOG_UNIT_COST * 100
            ELSE 0 END)))) +
        ((1 - DIV0NULL(COUNT(DISTINCT CASE WHEN po_rej.PO_ID IS NOT NULL THEN po_rej.PO_ID END),
            NULLIF(COUNT(DISTINCT pd.PO_ID), 0))) * 30)
    , 1) AS SUPPLIER_SCORE
FROM MFGPULSE_DB.RAW_IT.SUPPLIERS s
LEFT JOIN po_delivery pd ON s.SUPPLIER_ID = pd.SUPPLIER_ID
LEFT JOIN (
    SELECT PO_ID FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS WHERE REJECTION_REASON IS NOT NULL
) po_rej ON pd.PO_ID = po_rej.PO_ID
WHERE s.ACTIVE = TRUE
GROUP BY s.SUPPLIER_ID, s.SUPPLIER_NAME, s.CONTACT_EMAIL;
