-- ============================================================================
-- MFGPulse AI: 18 Validation
-- Full verification suite — Phase 7
-- ============================================================================

USE DATABASE MFGPULSE_DB;

-- 1. Schema existence (7 schemas)
SELECT 'SCHEMA' AS OBJ_TYPE, SCHEMA_NAME, 'PASS' AS STATUS
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('RAW_OT','RAW_IT','CURATED','ML_FEATURES','ML_MODELS','ANALYTICS','AGENT')
ORDER BY SCHEMA_NAME;

-- 2a. Row count validation
SELECT TABLE_NAME, CNT,
    CASE
        WHEN TABLE_NAME = 'ASSET_MASTER' AND CNT = 10 THEN 'PASS'
        WHEN TABLE_NAME = 'SENSOR_METADATA' AND CNT = 23 THEN 'PASS'
        WHEN TABLE_NAME = 'PARTS_INVENTORY' AND CNT >= 15 THEN 'PASS'
        WHEN TABLE_NAME = 'USERS' AND CNT >= 8 THEN 'PASS'
        WHEN TABLE_NAME = 'SENSOR_READINGS' AND CNT > 170000 THEN 'PASS'
        WHEN TABLE_NAME = 'WORK_ORDERS' AND CNT >= 22 THEN 'PASS'
        WHEN TABLE_NAME = 'MAINTENANCE_LOGS' AND CNT >= 26 THEN 'PASS'
        WHEN TABLE_NAME = 'SUPPLIERS' AND CNT >= 5 THEN 'PASS'
        WHEN TABLE_NAME = 'PART_SUPPLIERS' AND CNT >= 16 THEN 'PASS'
        WHEN TABLE_NAME = 'MODEL_REGISTRY' AND CNT = 12 THEN 'PASS'
        ELSE 'CHECK'
    END AS STATUS
FROM (
    SELECT 'ASSET_MASTER' AS TABLE_NAME, COUNT(*) AS CNT FROM RAW_OT.ASSET_MASTER
    UNION ALL SELECT 'SENSOR_METADATA', COUNT(*) FROM RAW_OT.SENSOR_METADATA
    UNION ALL SELECT 'PARTS_INVENTORY', COUNT(*) FROM RAW_IT.PARTS_INVENTORY
    UNION ALL SELECT 'USERS', COUNT(*) FROM RAW_IT.USERS
    UNION ALL SELECT 'SENSOR_READINGS', COUNT(*) FROM RAW_OT.SENSOR_READINGS
    UNION ALL SELECT 'WORK_ORDERS', COUNT(*) FROM RAW_IT.WORK_ORDERS
    UNION ALL SELECT 'MAINTENANCE_LOGS', COUNT(*) FROM RAW_IT.MAINTENANCE_LOGS
    UNION ALL SELECT 'SUPPLIERS', COUNT(*) FROM RAW_IT.SUPPLIERS
    UNION ALL SELECT 'PART_SUPPLIERS', COUNT(*) FROM RAW_IT.PART_SUPPLIERS
    UNION ALL SELECT 'MODEL_REGISTRY', COUNT(*) FROM ML_MODELS.MODEL_REGISTRY
) t ORDER BY TABLE_NAME;

-- 2b. Date range validation
SELECT SOURCE_TABLE, MIN_DT, MAX_DT,
    CASE WHEN MIN_DT >= '2026-03-01' AND MAX_DT <= '2026-09-30' THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'WORK_ORDERS' AS SOURCE_TABLE, MIN(created_date)::DATE AS MIN_DT, MAX(created_date)::DATE AS MAX_DT FROM RAW_IT.WORK_ORDERS
    UNION ALL SELECT 'MAINTENANCE_LOGS', MIN(timestamp)::DATE, MAX(timestamp)::DATE FROM RAW_IT.MAINTENANCE_LOGS
    UNION ALL SELECT 'PRODUCTION_OUTPUT', MIN(timestamp)::DATE, MAX(timestamp)::DATE FROM RAW_IT.PRODUCTION_OUTPUT
    UNION ALL SELECT 'SHIFT_SCHEDULE', MIN(shift_start)::DATE, MAX(shift_start)::DATE FROM RAW_IT.SHIFT_SCHEDULE
) t;

-- 2c. Referential integrity
SELECT 'SENSOR→ASSET' AS REL, COUNT(*) AS ORPHANS, CASE WHEN COUNT(*)=0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM RAW_OT.SENSOR_READINGS sr LEFT JOIN RAW_OT.ASSET_MASTER am ON sr.asset_id=am.asset_id WHERE am.asset_id IS NULL
UNION ALL
SELECT 'WO→ASSET', COUNT(*), CASE WHEN COUNT(*)=0 THEN 'PASS' ELSE 'FAIL' END
FROM RAW_IT.WORK_ORDERS wo LEFT JOIN RAW_OT.ASSET_MASTER am ON wo.asset_id=am.asset_id WHERE am.asset_id IS NULL;

-- 3. ML pipeline
SELECT 'LIVE_PREDICTIONS' AS OBJ, COUNT(*) AS CNT, CASE WHEN COUNT(*)=10 THEN 'PASS' ELSE 'FAIL' END AS STATUS FROM ML_MODELS.LIVE_PREDICTIONS
UNION ALL SELECT 'FATIGUE_SCORES', COUNT(*), CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'FAIL' END FROM ML_MODELS.FATIGUE_SCORES
UNION ALL SELECT 'ANOMALY_SCORES', COUNT(*), CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'FAIL' END FROM ML_MODELS.ANOMALY_SCORES
UNION ALL SELECT 'MODEL_REGISTRY', COUNT(*), CASE WHEN COUNT(*)=12 THEN 'PASS' ELSE 'FAIL' END FROM ML_MODELS.MODEL_REGISTRY;

-- 4. Prediction ranges valid
SELECT MIN(rul_hours) AS MIN_RUL, MAX(rul_hours) AS MAX_RUL,
    MIN(degradation_score) AS MIN_DEG, MAX(degradation_score) AS MAX_DEG,
    MIN(fatigue_score) AS MIN_FAT, MAX(fatigue_score) AS MAX_FAT,
    CASE WHEN MIN(rul_hours)>=0 AND MAX(degradation_score)<=1 AND MAX(fatigue_score)<=1 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM ML_MODELS.LIVE_PREDICTIONS;

-- 5. Analytics
SELECT 'ACTIVE_ALERTS' AS OBJ, COUNT(*) AS CNT, CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'WARN' END AS STATUS FROM ANALYTICS.ACTIVE_ALERTS
UNION ALL SELECT 'OEE_METRICS', COUNT(*), CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'FAIL' END FROM ANALYTICS.OEE_METRICS
UNION ALL SELECT 'PROCUREMENT_RECS', COUNT(*), CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'WARN' END FROM ANALYTICS.PROCUREMENT_RECOMMENDATIONS
UNION ALL SELECT 'PARTS_ATP', COUNT(*), CASE WHEN COUNT(*)>0 THEN 'PASS' ELSE 'WARN' END FROM ANALYTICS.PARTS_AVAILABLE_TO_PROMISE;

-- 6. UDF smoke tests
SELECT 'COMPUTE_FATIGUE' AS UDF, ML_MODELS.COMPUTE_FATIGUE_SCORE(3.5,0.5,5.0,65.0,0.5,0.03,48.0,0.3,500.0) AS RESULT,
    CASE WHEN ML_MODELS.COMPUTE_FATIGUE_SCORE(3.5,0.5,5.0,65.0,0.5,0.03,48.0,0.3,500.0) BETWEEN 0 AND 1 THEN 'PASS' ELSE 'FAIL' END AS STATUS;

-- 7. Personas
SELECT PERSONA, COUNT(*) AS USER_COUNT, 'PASS' AS STATUS
FROM RAW_IT.USERS WHERE ACTIVE=TRUE GROUP BY PERSONA ORDER BY PERSONA;

-- 8. Summary
SELECT
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME IN ('RAW_OT','RAW_IT','CURATED','ML_FEATURES','ML_MODELS','ANALYTICS','AGENT')) AS SCHEMAS,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC')) AS BASE_TABLES_AND_DTS,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='VIEW' AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC')) AS VIEWS,
    (SELECT COUNT(*) FROM RAW_OT.SENSOR_READINGS) AS SENSOR_READINGS,
    (SELECT COUNT(*) FROM ML_MODELS.LIVE_PREDICTIONS) AS PREDICTIONS,
    (SELECT COUNT(*) FROM ANALYTICS.ACTIVE_ALERTS) AS ALERTS,
    (SELECT COUNT(*) FROM ML_MODELS.MODEL_REGISTRY) AS ML_MODELS_REG,
    (SELECT COUNT(*) FROM RAW_IT.USERS WHERE ACTIVE=TRUE) AS ACTIVE_USERS;
