-- ============================================================================
-- MFGPulse AI: One-Time Deployment Script
-- ============================================================================
-- Deploys the entire platform from zero on a clean Snowflake account.
-- Logs every checkpoint with timing and credit usage to DEPLOYMENT_LOG.
--
-- Prerequisites:
--   - ACCOUNTADMIN role
--   - Cortex AI enabled (Complete, Search, Agent, Semantic Views)
--   - SYSTEM_COMPUTE_POOL_CPU compute pool exists
--
-- Execution: Run each section (delimited by checkpoint comments) one at a time.
-- Each section ends with an INSERT INTO DEPLOYMENT_LOG to record the checkpoint.
--
-- Estimated total: ~12-15 minutes, ~0.20 credits
-- ============================================================================

USE ROLE ACCOUNTADMIN;


-- ============================================================================
-- CHECKPOINT 0: DEPLOYMENT LOG TABLE
-- ============================================================================
-- Create a temporary tracking table in the session before the DB exists.
-- We'll move it into MFGPULSE_DB after Phase 1.

CREATE DATABASE IF NOT EXISTS MFGPULSE_DB;
USE DATABASE MFGPULSE_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE OR REPLACE TABLE MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG (
    CHECKPOINT_ID   INT,
    CHECKPOINT_NAME VARCHAR(100),
    STARTED_AT      TIMESTAMP_NTZ,
    COMPLETED_AT    TIMESTAMP_NTZ,
    DURATION_SEC    FLOAT,
    CREDITS_BEFORE  FLOAT,
    CREDITS_AFTER   FLOAT,
    CREDITS_USED    FLOAT,
    OBJECTS_CREATED INT,
    VALIDATION      VARCHAR(20),  -- PASS / FAIL / SKIP
    DETAILS         VARCHAR(2000)
);

-- Helper: snapshot current warehouse credits
CREATE OR REPLACE FUNCTION MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()
RETURNS FLOAT
LANGUAGE SQL
AS $$
    SELECT COALESCE(SUM(CREDITS_USED), 0)
    FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY(
        DATE_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
        WAREHOUSE_NAME => 'COMPUTE_WH'
    ))
$$;

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES
    (0, 'DEPLOYMENT_LOG_CREATED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 0, 0, 0, 2, 'PASS', 'Log table and credit helper function created');


-- ============================================================================
-- CHECKPOINT 1: INFRASTRUCTURE
-- DB, 7 schemas, 2 warehouses, 2 resource monitors
-- Source: deploy_all.sql lines 14-62
-- ============================================================================
SET cp1_start = CURRENT_TIMESTAMP();
SET cp1_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- Schemas
CREATE SCHEMA IF NOT EXISTS RAW_OT;
CREATE SCHEMA IF NOT EXISTS RAW_IT;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS ML_FEATURES;
CREATE SCHEMA IF NOT EXISTS ML_MODELS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS AGENT;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS MFGPULSE_AUTOMATION_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for MFGPulse AI tasks and dynamic table refreshes.';

-- Resource monitors
CREATE RESOURCE MONITOR IF NOT EXISTS MFGPULSE_CREDIT_GUARD
    WITH CREDIT_QUOTA = 250 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = MFGPULSE_CREDIT_GUARD;

CREATE OR REPLACE RESOURCE MONITOR MFGPULSE_AUTOMATION_GUARD
    WITH CREDIT_QUOTA = 50 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE MFGPULSE_AUTOMATION_WH SET RESOURCE_MONITOR = MFGPULSE_AUTOMATION_GUARD;

USE WAREHOUSE COMPUTE_WH;

-- Validate
SET cp1_schemas = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.SCHEMATA
    WHERE SCHEMA_NAME IN ('RAW_OT','RAW_IT','CURATED','ML_FEATURES','ML_MODELS','ANALYTICS','AGENT'));

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    1, 'INFRASTRUCTURE', $cp1_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp1_start, CURRENT_TIMESTAMP()),
    $cp1_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp1_credits_before,
    11, -- 1 DB + 7 schemas + 2 WH + 2 monitors - 1 (DB already existed)
    CASE WHEN $cp1_schemas = 7 THEN 'PASS' ELSE 'FAIL' END,
    'Schemas: ' || $cp1_schemas || '/7. DB + schemas + warehouses + monitors created.'
);


-- ============================================================================
-- CHECKPOINT 2: BASE TABLES
-- 21 base tables + 2 notification tables across RAW_OT, RAW_IT, ML_MODELS, ANALYTICS
-- Source: deploy_all.sql lines 66-253
-- ============================================================================
SET cp2_start = CURRENT_TIMESTAMP();
SET cp2_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- === RAW_OT ===
CREATE OR REPLACE TABLE RAW_OT.ASSET_MASTER (
    ASSET_ID VARCHAR(20) NOT NULL PRIMARY KEY, ASSET_NAME VARCHAR(100) NOT NULL,
    ASSET_TYPE VARCHAR(50) NOT NULL, LINE_ID VARCHAR(20) NOT NULL,
    INSTALL_DATE DATE, MANUFACTURER VARCHAR(100), MODEL_NUMBER VARCHAR(50),
    RATED_RPM FLOAT, RATED_TEMP_MAX FLOAT);

CREATE OR REPLACE TABLE RAW_OT.SENSOR_METADATA (
    SENSOR_ID VARCHAR(30) NOT NULL PRIMARY KEY, ASSET_ID VARCHAR(20) NOT NULL,
    SENSOR_TYPE VARCHAR(50) NOT NULL, LOCATION VARCHAR(100),
    CALIBRATION_DATE DATE, SAMPLING_RATE_HZ FLOAT);

CREATE OR REPLACE TABLE RAW_OT.SENSOR_READINGS (
    READING_ID NUMBER AUTOINCREMENT, ASSET_ID VARCHAR(20) NOT NULL,
    TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    VIBRATION_X FLOAT, VIBRATION_Y FLOAT, VIBRATION_Z FLOAT,
    TEMPERATURE FLOAT, RPM FLOAT, PRESSURE FLOAT,
    CURRENT_AMPS FLOAT, ACOUSTIC_DB FLOAT,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW_OT.AMBIENT_CONDITIONS (
    READING_DATE DATE NOT NULL, AMBIENT_TEMP_C FLOAT, HUMIDITY_PCT FLOAT, BAROMETRIC_PRESSURE_HPA FLOAT);

-- === RAW_IT ===
CREATE OR REPLACE TABLE RAW_IT.WORK_ORDERS (
    WO_ID VARCHAR(50) NOT NULL PRIMARY KEY, ASSET_ID VARCHAR(20) NOT NULL,
    WO_TYPE VARCHAR(20) NOT NULL, CREATED_DATE TIMESTAMP_NTZ NOT NULL,
    COMPLETED_DATE TIMESTAMP_NTZ, PRIORITY VARCHAR(10), STATUS VARCHAR(20),
    ASSIGNED_TO VARCHAR(100), LABOR_HOURS FLOAT, PARTS_COST FLOAT, TOTAL_COST FLOAT,
    ROOT_CAUSE_CONFIRMED VARCHAR, PART_USED BOOLEAN DEFAULT TRUE);

CREATE OR REPLACE TABLE RAW_IT.MAINTENANCE_LOGS (
    LOG_ID VARCHAR(20) NOT NULL PRIMARY KEY, WO_ID VARCHAR(20),
    ASSET_ID VARCHAR(20) NOT NULL, TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TECHNICIAN VARCHAR(100), NOTES_TEXT VARCHAR(2000));

CREATE OR REPLACE TABLE RAW_IT.PRODUCTION_OUTPUT (
    RECORD_ID VARCHAR(20) NOT NULL PRIMARY KEY, ASSET_ID VARCHAR(20) NOT NULL,
    SHIFT_ID VARCHAR(20), TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    UNITS_PRODUCED INT, GOOD_UNITS INT, IDEAL_CYCLE_TIME_SEC FLOAT);

CREATE OR REPLACE TABLE RAW_IT.SHIFT_SCHEDULE (
    SHIFT_ID VARCHAR(20) NOT NULL PRIMARY KEY, LINE_ID VARCHAR(20) NOT NULL,
    SHIFT_START TIMESTAMP_NTZ NOT NULL, SHIFT_END TIMESTAMP_NTZ NOT NULL,
    OPERATOR_NAME VARCHAR(100), PLANNED_PRODUCTION_TIME_MINS INT);

CREATE OR REPLACE TABLE RAW_IT.PARTS_INVENTORY (
    PART_ID VARCHAR(20) NOT NULL PRIMARY KEY, PART_NAME VARCHAR(200) NOT NULL,
    COMPATIBLE_ASSETS ARRAY, QUANTITY_ON_HAND INT, LEAD_TIME_DAYS INT, UNIT_COST FLOAT);

CREATE OR REPLACE TABLE RAW_IT.USERS (
    USER_ID VARCHAR(20) NOT NULL PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200), PERSONA VARCHAR(50) NOT NULL, ROLE VARCHAR(50),
    LINE_ID VARCHAR(20), ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW_IT.SUPPLIERS (
    SUPPLIER_ID VARCHAR(20) NOT NULL PRIMARY KEY, SUPPLIER_NAME VARCHAR(200) NOT NULL,
    CONTACT_EMAIL VARCHAR(200), PHONE VARCHAR(50),
    ACTIVE BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW_IT.PART_SUPPLIERS (
    PART_ID VARCHAR(20) NOT NULL, SUPPLIER_ID VARCHAR(20) NOT NULL,
    SUPPLIER_PART_NUMBER VARCHAR(50),
    STANDARD_LEAD_TIME_DAYS INT DEFAULT 7, EXPEDITE_LEAD_TIME_DAYS INT DEFAULT 3,
    MIN_ORDER_QTY INT DEFAULT 1, UNIT_COST FLOAT, PREFERRED_SUPPLIER BOOLEAN DEFAULT FALSE);

CREATE OR REPLACE TABLE RAW_IT.PART_RESERVATIONS (
    RESERVATION_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    PART_ID VARCHAR(20) NOT NULL, ASSET_ID VARCHAR(20) NOT NULL,
    WO_ID VARCHAR(50), QUANTITY_RESERVED INT DEFAULT 1,
    REQUIRED_BY_DATE DATE, STATUS VARCHAR(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW_IT.PURCHASE_ORDERS (
    PO_ID VARCHAR(50) NOT NULL PRIMARY KEY, SUPPLIER_ID VARCHAR(20),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REQUIRED_BY_DATE DATE, EXPECTED_ARRIVAL_DATE DATE,
    STATUS VARCHAR(30) DEFAULT 'draft', PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
    TOTAL_COST FLOAT, CREATED_BY VARCHAR(100) DEFAULT 'SYSTEM',
    SOURCE VARCHAR(30) DEFAULT 'prediction',
    REJECTION_REASON VARCHAR, REJECTED_BY VARCHAR, REJECTED_AT TIMESTAMP_NTZ);

CREATE OR REPLACE TABLE RAW_IT.PURCHASE_ORDER_LINES (
    PO_LINE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    PO_ID VARCHAR(50) NOT NULL, PART_ID VARCHAR(20) NOT NULL,
    ASSET_ID VARCHAR(20), WO_ID VARCHAR(50),
    QUANTITY_ORDERED INT DEFAULT 1, UNIT_COST FLOAT, LINE_COST FLOAT,
    RUL_HOURS_AT_ORDER FLOAT, FAILURE_MODE_PRED VARCHAR(50), PROCUREMENT_RISK VARCHAR(30));

CREATE TABLE IF NOT EXISTS RAW_IT.SIMULATION_CONFIG (
    CONFIG_ID INT AUTOINCREMENT PRIMARY KEY, ASSET_ID VARCHAR(20) NOT NULL,
    SCENARIO VARCHAR(30) NOT NULL, SEVERITY FLOAT DEFAULT 0.0, HOURS INT DEFAULT 12,
    STATUS VARCHAR(20) DEFAULT 'PENDING', ROWS_GENERATED INT DEFAULT 0,
    ESTIMATED_CREDITS FLOAT DEFAULT 0, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(), COMPLETED_AT TIMESTAMP_NTZ);

-- === ML_MODELS ===
CREATE OR REPLACE TABLE ML_MODELS.MODEL_REGISTRY (
    MODEL_NAME VARCHAR(100), MODEL_TYPE VARCHAR(100), TRAINING_DATA VARCHAR(200),
    PRECISION_SCORE FLOAT, RECALL_SCORE FLOAT, F1_SCORE FLOAT,
    TOP_FEATURES VARCHAR(500), TRAINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE ML_MODELS.FATIGUE_SCORES (
    ASSET_ID VARCHAR(20), TIMESTAMP TIMESTAMP_NTZ,
    FATIGUE_SCORE FLOAT, FATIGUE_LEVEL VARCHAR(20));

CREATE OR REPLACE TABLE ML_MODELS.ANOMALY_SCORES (
    SERIES VARIANT, TS TIMESTAMP_NTZ, Y FLOAT, FORECAST FLOAT,
    LOWER_BOUND FLOAT, UPPER_BOUND FLOAT,
    IS_ANOMALY BOOLEAN, PERCENTILE FLOAT, DISTANCE FLOAT);

CREATE OR REPLACE TABLE ANALYTICS.SHIFT_HANDOVER_HISTORY (
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SUMMARY_TEXT TEXT, WOS_GENERATED INT, PLANT_OEE FLOAT, CRITICAL_ASSETS INT);

-- Notification tables
CREATE TABLE IF NOT EXISTS RAW_IT.NOTIFICATION_SETTINGS (
    EVENT_TYPE VARCHAR(30) NOT NULL PRIMARY KEY, EVENT_LABEL VARCHAR(100),
    EMAIL_ENABLED BOOLEAN DEFAULT FALSE, IN_APP_ENABLED BOOLEAN DEFAULT TRUE,
    EMAIL_RECIPIENTS VARCHAR(500) DEFAULT '', NOTIFY_PERSONAS VARCHAR(200) DEFAULT 'PLANT_MANAGER,APP_ADMIN',
    PRIORITY VARCHAR(10) DEFAULT 'NORMAL',
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_BY VARCHAR(100) DEFAULT CURRENT_USER());

CREATE TABLE IF NOT EXISTS RAW_IT.APP_NOTIFICATIONS (
    NOTIF_ID VARCHAR(200) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), EVENT_TYPE VARCHAR(50) NOT NULL,
    PERSONA_TARGET VARCHAR(50),
    TITLE VARCHAR(500), MESSAGE VARCHAR(2000), ENTITY_ID VARCHAR(100),
    PRIORITY VARCHAR(20) DEFAULT 'NORMAL', IS_READ BOOLEAN DEFAULT FALSE, DISMISSED BOOLEAN DEFAULT FALSE);

-- Validate
SET cp2_tables = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC'));

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    2, 'BASE_TABLES', $cp2_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp2_start, CURRENT_TIMESTAMP()),
    $cp2_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp2_credits_before,
    $cp2_tables, CASE WHEN $cp2_tables >= 21 THEN 'PASS' ELSE 'FAIL' END,
    'Tables created: ' || $cp2_tables || '/23 (incl notification + simulation tables).'
);


-- ============================================================================
-- CHECKPOINT 3: STREAMS
-- ============================================================================
SET cp3_start = CURRENT_TIMESTAMP();
SET cp3_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

CREATE OR REPLACE STREAM RAW_OT.SENSOR_READINGS_STREAM ON TABLE RAW_OT.SENSOR_READINGS APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW_IT.MAINTENANCE_LOGS_STREAM ON TABLE RAW_IT.MAINTENANCE_LOGS APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW_IT.WORK_ORDERS_STREAM ON TABLE RAW_IT.WORK_ORDERS;

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    3, 'STREAMS', $cp3_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp3_start, CURRENT_TIMESTAMP()),
    $cp3_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp3_credits_before,
    3, 'PASS', '3 CDC streams created on SENSOR_READINGS, MAINTENANCE_LOGS, WORK_ORDERS.'
);


-- ============================================================================
-- CHECKPOINT 4: SEED DATA
-- Run sql/04_seed_data.sql in a separate worksheet, then come back here.
-- Expected: ASSET_MASTER=10, SENSOR_METADATA=23, USERS=9, PARTS=15,
--   MODEL_REGISTRY=12, WOs=22, LOGS=26, SHIFTS~1710, PRODUCTION~3330
-- ============================================================================
-- >>> RUN sql/04_seed_data.sql NOW <<<

SET cp4_start = CURRENT_TIMESTAMP();
SET cp4_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- Validate seed data
SET cp4_assets   = (SELECT COUNT(*) FROM RAW_OT.ASSET_MASTER);
SET cp4_sensors  = (SELECT COUNT(*) FROM RAW_OT.SENSOR_METADATA);
SET cp4_users    = (SELECT COUNT(*) FROM RAW_IT.USERS);
SET cp4_parts    = (SELECT COUNT(*) FROM RAW_IT.PARTS_INVENTORY);
SET cp4_models   = (SELECT COUNT(*) FROM ML_MODELS.MODEL_REGISTRY);
SET cp4_wos      = (SELECT COUNT(*) FROM RAW_IT.WORK_ORDERS);
SET cp4_logs     = (SELECT COUNT(*) FROM RAW_IT.MAINTENANCE_LOGS);
SET cp4_shifts   = (SELECT COUNT(*) FROM RAW_IT.SHIFT_SCHEDULE);
SET cp4_prod     = (SELECT COUNT(*) FROM RAW_IT.PRODUCTION_OUTPUT);

SET cp4_pass = (CASE WHEN $cp4_assets = 10 AND $cp4_sensors = 23 AND $cp4_users >= 8
    AND $cp4_parts = 15 AND $cp4_models = 12 AND $cp4_wos >= 22
    AND $cp4_logs >= 26 AND $cp4_shifts > 1000 AND $cp4_prod > 2000
    THEN 'PASS' ELSE 'FAIL' END);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    4, 'SEED_DATA', $cp4_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp4_start, CURRENT_TIMESTAMP()),
    $cp4_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp4_credits_before,
    $cp4_assets + $cp4_sensors + $cp4_users + $cp4_parts + $cp4_models + $cp4_wos + $cp4_logs,
    $cp4_pass,
    'Assets=' || $cp4_assets || ' Sensors=' || $cp4_sensors || ' Users=' || $cp4_users
    || ' Parts=' || $cp4_parts || ' Models=' || $cp4_models || ' WOs=' || $cp4_wos
    || ' Logs=' || $cp4_logs || ' Shifts=' || $cp4_shifts || ' Production=' || $cp4_prod
);


-- ============================================================================
-- CHECKPOINT 5: SENSOR DATA GENERATION
-- Creates procedure and generates 172K+ sensor readings
-- Source: deploy_all.sql lines 326-412
-- ============================================================================
-- >>> RUN sql/05_generate_sensor_data.sql NOW (creates the procedure) <<<
-- Then execute:

SET cp5_start = CURRENT_TIMESTAMP();
SET cp5_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

CALL MFGPULSE_DB.RAW_OT.GENERATE_SENSOR_DATA();

SET cp5_readings = (SELECT COUNT(*) FROM RAW_OT.SENSOR_READINGS);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    5, 'SENSOR_DATA_GENERATION', $cp5_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp5_start, CURRENT_TIMESTAMP()),
    $cp5_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp5_credits_before,
    $cp5_readings,
    CASE WHEN $cp5_readings > 170000 THEN 'PASS' ELSE 'FAIL' END,
    'Sensor readings generated: ' || $cp5_readings || ' (expected >170,000).'
);


-- ============================================================================
-- CHECKPOINT 6: UDFs AND CORE ML PROCEDURES
-- Source: docs/full_ddl_export.sql lines 2304-2336 (UDFs), 2689-2810 (UDFs),
--         2135-2303 (ANALYZE_ROOT_CAUSE), 2803-2838 (PRESCRIBE_MAINTENANCE),
--         2434-2546 (GENERATE_PRESCRIPTION), 2547-2688 (PREDICT_ALL),
--         2936-3010 (SIMULATE_FAILURE_TWIN)
-- ============================================================================
-- >>> RUN the following sections from docs/full_ddl_export.sql:
--     Lines 2304-2336: COMPUTE_FATIGUE_SCORE UDF
--     Lines 2689-2723: PREDICT_DEGRADATION_STAGE UDF
--     Lines 2724-2761: PREDICT_FAILURE_MODE UDF
--     Lines 2762-2802: PREDICT_RUL UDF
--     Lines 2936-3010: SIMULATE_FAILURE_TWIN UDF
--     Lines 2135-2232: ANALYZE_ROOT_CAUSE procedure (NUMBER overload)
--     Lines 2233-2303: ANALYZE_ROOT_CAUSE procedure (VARCHAR overload)
--     Lines 2434-2546: GENERATE_PRESCRIPTION procedure
--     Lines 2803-2838: PRESCRIBE_MAINTENANCE procedure
--     Lines 2547-2688: PREDICT_ALL procedure
-- ALTERNATIVELY: Run sql/ddl_objects.sql for the UDFs + partial procs,
--   then supplement with full_ddl_export.sql for ANALYZE_ROOT_CAUSE and PREDICT_ALL.

SET cp6_start = CURRENT_TIMESTAMP();
SET cp6_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- After running the above, validate:
SET cp6_udfs = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.FUNCTIONS
    WHERE FUNCTION_SCHEMA = 'ML_MODELS');
SET cp6_procs = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.PROCEDURES
    WHERE PROCEDURE_SCHEMA = 'ML_MODELS');

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    6, 'UDFS_AND_ML_PROCEDURES', $cp6_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp6_start, CURRENT_TIMESTAMP()),
    $cp6_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp6_credits_before,
    $cp6_udfs + $cp6_procs,
    CASE WHEN $cp6_udfs >= 5 AND $cp6_procs >= 3 THEN 'PASS' ELSE 'FAIL' END,
    'UDFs: ' || $cp6_udfs || '/5, ML Procedures: ' || $cp6_procs || '/4+'
);


-- ============================================================================
-- CHECKPOINT 7: DYNAMIC TABLES (Layer 1-2: Curated + ML Features)
-- Source: docs/full_ddl_export.sql
-- DEPENDENCY ORDER:
--   Layer 1 (base tables only):
--     CURATED.SENSOR_WITH_CONTEXT    (lines 860-913)
--     CURATED.ASSET_HEALTH_CURRENT   (lines 695-781)
--     CURATED.FAILURE_HISTORY        (lines 782-859)
--   Layer 2 (depends on CURATED DTs):
--     ML_FEATURES.ROLLING_STATS          (lines 1245-1374)
--     ML_FEATURES.SENSOR_INTERACTIONS    (lines 1375-1437)
--     ML_FEATURES.PHYSICS_COMPOSITE      (lines 1165-1244)
--     ML_FEATURES.TEMPORAL_MEMORY        (lines 1438-1526)
--     ML_FEATURES.CROSS_DOMAIN           (lines 916-1007)
--     ML_FEATURES.FLEET_COMPARISON       (lines 1008-1064)
--     ML_FEATURES.LABELED_DATA           (lines 1065-1164)
-- ============================================================================
-- >>> RUN the above sections from docs/full_ddl_export.sql in the listed order.
-- NOTE: Add schema qualifiers if running from a different schema context:
--   USE SCHEMA CURATED; before CURATED DTs
--   USE SCHEMA ML_FEATURES; before ML_FEATURES DTs
-- Wait 3-5 minutes for initial refresh after creation.

SET cp7_start = CURRENT_TIMESTAMP();
SET cp7_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- After DTs are created and refreshed, validate:
SET cp7_dts = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'DYNAMIC TABLE' AND TABLE_SCHEMA IN ('CURATED','ML_FEATURES'));

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    7, 'DYNAMIC_TABLES_L1_L2', $cp7_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp7_start, CURRENT_TIMESTAMP()),
    $cp7_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp7_credits_before,
    $cp7_dts,
    CASE WHEN $cp7_dts >= 10 THEN 'PASS' ELSE 'FAIL' END,
    'Curated + ML Feature DTs: ' || $cp7_dts || '/10. Wait for initial refresh to complete.'
);


-- ============================================================================
-- CHECKPOINT 8: ML FEATURE VIEWS + LIVE_PREDICTIONS DT
-- Source: docs/full_ddl_export.sql
--   USE SCHEMA ML_FEATURES;
--     ALL_DERIVED_FEATURES            (lines 1527-1570)
--     ALL_DERIVED_FEATURES_INFERENCE  (lines 1571-1592)
--     FEATURE_CATALOG                 (lines 1593-1629)
--     HEALTHY_DERIVED_FEATURES        (lines 1630-1678)
--     HEALTHY_DERIVED_FEATURES_TRAIN  (lines 1679-1700)
--     TRAIN_ANOMALY                   (lines 1701-1737)
--     TRAIN_ANOMALY_SMALL             (lines 1738-1763)
--     TRAIN_FAILURE_MODE              (lines 1764-1818)
--     TRAIN_RUL                       (lines 1819-1876)
--     TRAIN_TRAJECTORY                (lines 1877-1926)
--     TRAIN_TRAJECTORY_3CLASS         (lines 1927-1982)
--   USE SCHEMA ML_MODELS;
--     LIVE_PREDICTIONS DT             (lines 2002-2134)
-- ============================================================================
-- >>> RUN the above from docs/full_ddl_export.sql <<<
-- Wait 1-2 minutes for LIVE_PREDICTIONS to refresh (should show 10 rows).

SET cp8_start = CURRENT_TIMESTAMP();
SET cp8_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

SET cp8_views = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = 'ML_FEATURES');
SET cp8_lp = (SELECT COUNT(*) FROM ML_MODELS.LIVE_PREDICTIONS);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    8, 'ML_VIEWS_AND_LIVE_PREDICTIONS', $cp8_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp8_start, CURRENT_TIMESTAMP()),
    $cp8_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp8_credits_before,
    $cp8_views + 1,
    CASE WHEN $cp8_views >= 11 AND $cp8_lp = 10 THEN 'PASS' ELSE 'FAIL' END,
    'ML Feature Views: ' || $cp8_views || '/11, LIVE_PREDICTIONS rows: ' || $cp8_lp || '/10.'
);


-- ============================================================================
-- CHECKPOINT 9: ANALYTICS LAYER + PROCUREMENT VIEWS
-- Source: docs/full_ddl_export.sql (Analytics DTs + views)
--   USE SCHEMA ANALYTICS;
--     ACTIVE_ALERTS DT       (lines 11-123)
--     OEE_METRICS DT         (lines 124-208)
--     ALERT_SUMMARY view     (lines 209-222)
--     COST_IMPACT view       (lines 223-321)
--     COST_IMPACT_BY_ASSET   (lines 322-362)
--     EXECUTIVE_SUMMARY      (lines 363-408)
--     PREDICTIONS_WITH_COST  (lines 409-475)
--     SHIFT_HANDOVER_VIEW    (lines 476-527)
--
-- Then run the analytics procedures from docs/full_ddl_export.sql:
--     GENERATE_SHIFT_HANDOVER_SUMMARY (lines 556-633)
--     GENERATE_WORK_ORDER             (lines 634-694)
--     AUTO_GENERATE_WORK_ORDERS       (lines 528-555)
-- Also from ddl_objects.sql or full_ddl_export.sql:
--     GENERATE_PURCHASE_ORDER         (lines 3977-4045)
--     AUTO_GENERATE_PURCHASE_ORDERS   (lines 4048-4083)
--     RESERVE_PART_FOR_WORK_ORDER     (lines 4086-4105)
--     AUTO_CONVERT_PLANNED_POS        (lines 4108-4187)
--
-- Then run the 3 MISSING procurement views below:
-- ============================================================================
-- >>> RUN the above from docs/full_ddl_export.sql <<<
-- >>> THEN RUN the 3 procurement views below: <<<

-- PARTS_AVAILABLE_TO_PROMISE — ATP calculation per part
CREATE OR REPLACE VIEW ANALYTICS.PARTS_AVAILABLE_TO_PROMISE AS
SELECT
    pi.PART_ID,
    pi.PART_NAME,
    pi.QUANTITY_ON_HAND,
    COALESCE(r.RESERVED_QUANTITY, 0) AS RESERVED_QUANTITY,
    GREATEST(0, pi.QUANTITY_ON_HAND - COALESCE(r.RESERVED_QUANTITY, 0)) AS AVAILABLE_TO_PROMISE,
    pi.LEAD_TIME_DAYS,
    pi.UNIT_COST,
    COALESCE(ps.SUPPLIER_NAME, 'No Supplier') AS SUPPLIER_NAME,
    COALESCE(po_incoming.INCOMING_QTY, 0) AS INCOMING_PO_QTY
FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
LEFT JOIN (
    SELECT PART_ID, SUM(QUANTITY_RESERVED) AS RESERVED_QUANTITY
    FROM MFGPULSE_DB.RAW_IT.PART_RESERVATIONS
    WHERE STATUS = 'active'
    GROUP BY PART_ID
) r ON pi.PART_ID = r.PART_ID
LEFT JOIN (
    SELECT ps2.PART_ID, s.SUPPLIER_NAME
    FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2
    JOIN MFGPULSE_DB.RAW_IT.SUPPLIERS s ON ps2.SUPPLIER_ID = s.SUPPLIER_ID
    WHERE ps2.PREFERRED_SUPPLIER = TRUE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
) ps ON pi.PART_ID = ps.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, SUM(pol.QUANTITY_ORDERED) AS INCOMING_QTY
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS IN ('approved','ordered','shipped')
    GROUP BY pol.PART_ID
) po_incoming ON pi.PART_ID = po_incoming.PART_ID;


-- PROCUREMENT_RECOMMENDATIONS — per-asset, per-part procurement risk + action
CREATE OR REPLACE VIEW ANALYTICS.PROCUREMENT_RECOMMENDATIONS AS
WITH asset_predictions AS (
    SELECT lp.ASSET_ID, lp.ASSET_NAME, lp.FAILURE_MODE_PRED, lp.RUL_HOURS,
        lp.STAGE_PRED, lp.DEGRADATION_SCORE, lp.FATIGUE_SCORE
    FROM MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp
    WHERE lp.FAILURE_MODE_PRED != 'normal' OR lp.STAGE_PRED IN ('Warning','Critical')
),
compatible_parts AS (
    SELECT ap.ASSET_ID, ap.ASSET_NAME, ap.FAILURE_MODE_PRED, ap.RUL_HOURS,
        ap.STAGE_PRED, ap.DEGRADATION_SCORE, ap.FATIGUE_SCORE,
        pi.PART_ID, pi.PART_NAME, pi.UNIT_COST,
        pi.LEAD_TIME_DAYS
    FROM asset_predictions ap
    JOIN MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
      ON ARRAY_CONTAINS(ap.ASSET_ID::VARIANT, pi.COMPATIBLE_ASSETS)
),
competing_assets AS (
    SELECT pi2.PART_ID, COUNT(DISTINCT lp2.ASSET_ID) AS COMPETING_ASSETS
    FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi2
    JOIN MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp2
      ON ARRAY_CONTAINS(lp2.ASSET_ID::VARIANT, pi2.COMPATIBLE_ASSETS)
    WHERE lp2.FAILURE_MODE_PRED != 'normal' OR lp2.STAGE_PRED IN ('Warning','Critical')
    GROUP BY pi2.PART_ID
),
earliest_arrivals AS (
    SELECT pol.PART_ID, MIN(po.EXPECTED_ARRIVAL_DATE) AS EARLIEST_PO_ARRIVAL
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS NOT IN ('cancelled','received')
    GROUP BY pol.PART_ID
),
with_supply AS (
    SELECT cp.*,
        atp.AVAILABLE_TO_PROMISE,
        atp.INCOMING_PO_QTY,
        COALESCE(atp.SUPPLIER_NAME, 'Unknown') AS SUPPLIER_NAME,
        COALESCE(ps.SUPPLIER_ID, 'SUP-001') AS SUPPLIER_ID,
        1 AS REQUIRED_QUANTITY,
        atp.AVAILABLE_TO_PROMISE + atp.INCOMING_PO_QTY - 1 AS NET_POSITION,
        DATEADD('hour', GREATEST(cp.RUL_HOURS - 24, 0), CURRENT_TIMESTAMP())::DATE AS REQUIRED_BY_DATE,
        epo.OPEN_PO_ID,
        wo.WO_ID,
        COALESCE(ca.COMPETING_ASSETS, 1) AS COMPETING_ASSETS,
        ea.EARLIEST_PO_ARRIVAL
    FROM compatible_parts cp
    LEFT JOIN MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE atp ON cp.PART_ID = atp.PART_ID
    LEFT JOIN (
        SELECT ps2.PART_ID, ps2.SUPPLIER_ID
        FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2 WHERE ps2.PREFERRED_SUPPLIER = TRUE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
    ) ps ON cp.PART_ID = ps.PART_ID
    LEFT JOIN (
        SELECT pol.PART_ID, pol.ASSET_ID, po.PO_ID AS OPEN_PO_ID
        FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
        JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
        WHERE po.STATUS NOT IN ('cancelled','received')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY pol.PART_ID, pol.ASSET_ID ORDER BY po.CREATED_DATE DESC) = 1
    ) epo ON cp.PART_ID = epo.PART_ID AND cp.ASSET_ID = epo.ASSET_ID
    LEFT JOIN (
        SELECT ASSET_ID, WO_ID FROM MFGPULSE_DB.RAW_IT.WORK_ORDERS
        WHERE STATUS IN ('open','in_progress')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY CREATED_DATE DESC) = 1
    ) wo ON cp.ASSET_ID = wo.ASSET_ID
    LEFT JOIN competing_assets ca ON cp.PART_ID = ca.PART_ID
    LEFT JOIN earliest_arrivals ea ON cp.PART_ID = ea.PART_ID
)
SELECT
    ws.ASSET_ID, ws.ASSET_NAME, ws.PART_ID, ws.PART_NAME,
    ws.SUPPLIER_ID, ws.SUPPLIER_NAME,
    ws.RUL_HOURS, ws.STAGE_PRED, ws.FAILURE_MODE_PRED,
    ws.DEGRADATION_SCORE, ws.FATIGUE_SCORE,
    CASE
        WHEN ws.AVAILABLE_TO_PROMISE <= 0 AND ws.INCOMING_PO_QTY <= 0 THEN 'CRITICAL_SHORTAGE'
        WHEN ws.RUL_HOURS < 72 AND ws.AVAILABLE_TO_PROMISE < ws.REQUIRED_QUANTITY THEN 'EXPEDITE'
        WHEN ws.NET_POSITION < 0 THEN 'ORDER_NOW'
        WHEN ws.RUL_HOURS < 336 THEN 'ORDER_NOW'
        ELSE 'NO_RISK'
    END AS PROCUREMENT_RISK,
    CASE
        WHEN ws.OPEN_PO_ID IS NOT NULL THEN 'MONITOR_EXISTING_PO'
        WHEN ws.AVAILABLE_TO_PROMISE <= 0 AND ws.INCOMING_PO_QTY <= 0 THEN 'ESCALATE_CRITICAL_SHORTAGE'
        WHEN ws.RUL_HOURS < 72 THEN 'EXPEDITE_PO'
        WHEN ws.NET_POSITION < 0 OR ws.RUL_HOURS < 336 THEN 'CREATE_PO'
        WHEN ws.AVAILABLE_TO_PROMISE > 0 AND ws.RUL_HOURS < 200 THEN 'RESERVE_AND_ORDER'
        ELSE 'NO_ACTION'
    END AS RECOMMENDED_PROCUREMENT_ACTION,
    ws.OPEN_PO_ID, ws.WO_ID,
    ws.AVAILABLE_TO_PROMISE, ws.INCOMING_PO_QTY, ws.NET_POSITION,
    ws.REQUIRED_QUANTITY, ws.REQUIRED_BY_DATE,
    ws.LEAD_TIME_DAYS, ws.UNIT_COST,
    ws.COMPETING_ASSETS,
    CASE
        WHEN ws.NET_POSITION >= 2 THEN 'SURPLUS'
        WHEN ws.NET_POSITION >= 0 THEN 'TIGHT'
        ELSE 'DEFICIT'
    END AS BUFFER_STATUS,
    ws.LEAD_TIME_DAYS - CEIL(ws.RUL_HOURS / 24.0) AS LEAD_TIME_GAP_DAYS,
    ws.EARLIEST_PO_ARRIVAL
FROM with_supply ws;


-- PARTS_LIFECYCLE_INSIGHTS — part health, usage trends, and procurement history
CREATE OR REPLACE VIEW ANALYTICS.PARTS_LIFECYCLE_INSIGHTS AS
SELECT
    pi.PART_ID, pi.PART_NAME, pi.QUANTITY_ON_HAND, pi.UNIT_COST, pi.LEAD_TIME_DAYS,
    COALESCE(wo_usage.TIMES_USED, 0) AS TIMES_USED_IN_WOS,
    COALESCE(wo_usage.TOTAL_WO_COST, 0) AS TOTAL_WO_COST_INVOLVING_PART,
    COALESCE(po_history.TOTAL_ORDERED, 0) AS TOTAL_ORDERED_HISTORICALLY,
    COALESCE(po_history.LAST_ORDERED_DATE, NULL) AS LAST_ORDERED_DATE,
    COALESCE(res.ACTIVE_RESERVATIONS, 0) AS ACTIVE_RESERVATIONS,
    COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND) AS AVAILABLE_TO_PROMISE,
    CASE
        WHEN pi.QUANTITY_ON_HAND = 0 THEN 'OUT_OF_STOCK'
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND) <= 1 THEN 'LOW_STOCK'
        WHEN pi.LEAD_TIME_DAYS > 14 THEN 'LONG_LEAD_TIME'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS,
    ARRAY_SIZE(pi.COMPATIBLE_ASSETS) AS COMPATIBLE_ASSET_COUNT,
    ps.SUPPLIER_NAME AS PREFERRED_SUPPLIER,
    COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) AS AT_RISK_ASSET_COUNT,
    COALESCE(at_risk.AT_RISK_ASSETS, '') AS AT_RISK_ASSETS,
    COALESCE(atp.INCOMING_PO_QTY, 0) AS INCOMING_QTY,
    COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
        + COALESCE(atp.INCOMING_PO_QTY, 0)
        - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) AS NET_POSITION,
    CASE
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
             + COALESCE(atp.INCOMING_PO_QTY, 0)
             - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) >= 2 THEN 'SURPLUS'
        WHEN COALESCE(atp.AVAILABLE_TO_PROMISE, pi.QUANTITY_ON_HAND)
             + COALESCE(atp.INCOMING_PO_QTY, 0)
             - COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) >= 0 THEN 'TIGHT'
        ELSE 'DEFICIT'
    END AS BUFFER_STATUS,
    CASE
        WHEN COALESCE(at_risk.AT_RISK_ASSET_COUNT, 0) = 0 THEN NULL
        ELSE ROUND(COALESCE(at_risk.MIN_RUL_HOURS, 0) / 24.0, 1)
    END AS EST_DAYS_UNTIL_STOCKOUT,
    ROUND(COALESCE(at_risk.MIN_RUL_HOURS, 0) / 24.0, 1) AS MIN_RUL_DAYS,
    po_arrival.EARLIEST_ARRIVAL
FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi
LEFT JOIN (
    SELECT pol.PART_ID, COUNT(DISTINCT wo.WO_ID) AS TIMES_USED, SUM(wo.TOTAL_COST) AS TOTAL_WO_COST
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.WORK_ORDERS wo ON pol.WO_ID = wo.WO_ID
    GROUP BY pol.PART_ID
) wo_usage ON pi.PART_ID = wo_usage.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, SUM(pol.QUANTITY_ORDERED) AS TOTAL_ORDERED, MAX(po.CREATED_DATE) AS LAST_ORDERED_DATE
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    GROUP BY pol.PART_ID
) po_history ON pi.PART_ID = po_history.PART_ID
LEFT JOIN (
    SELECT PART_ID, COUNT(*) AS ACTIVE_RESERVATIONS
    FROM MFGPULSE_DB.RAW_IT.PART_RESERVATIONS WHERE STATUS = 'active'
    GROUP BY PART_ID
) res ON pi.PART_ID = res.PART_ID
LEFT JOIN MFGPULSE_DB.ANALYTICS.PARTS_AVAILABLE_TO_PROMISE atp ON pi.PART_ID = atp.PART_ID
LEFT JOIN (
    SELECT ps2.PART_ID, s.SUPPLIER_NAME
    FROM MFGPULSE_DB.RAW_IT.PART_SUPPLIERS ps2
    JOIN MFGPULSE_DB.RAW_IT.SUPPLIERS s ON ps2.SUPPLIER_ID = s.SUPPLIER_ID
    WHERE ps2.PREFERRED_SUPPLIER = TRUE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ps2.PART_ID ORDER BY ps2.UNIT_COST) = 1
) ps ON pi.PART_ID = ps.PART_ID
LEFT JOIN (
    SELECT pi2.PART_ID,
        COUNT(DISTINCT lp.ASSET_ID) AS AT_RISK_ASSET_COUNT,
        LISTAGG(DISTINCT lp.ASSET_NAME, ', ') WITHIN GROUP (ORDER BY lp.ASSET_NAME) AS AT_RISK_ASSETS,
        MIN(lp.RUL_HOURS) AS MIN_RUL_HOURS
    FROM MFGPULSE_DB.RAW_IT.PARTS_INVENTORY pi2
    JOIN MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS lp
      ON ARRAY_CONTAINS(lp.ASSET_ID::VARIANT, pi2.COMPATIBLE_ASSETS)
    WHERE lp.FAILURE_MODE_PRED != 'normal' OR lp.STAGE_PRED IN ('Warning','Critical')
    GROUP BY pi2.PART_ID
) at_risk ON pi.PART_ID = at_risk.PART_ID
LEFT JOIN (
    SELECT pol.PART_ID, MIN(po.EXPECTED_ARRIVAL_DATE) AS EARLIEST_ARRIVAL
    FROM MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES pol
    JOIN MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS po ON pol.PO_ID = po.PO_ID
    WHERE po.STATUS NOT IN ('cancelled','received')
    GROUP BY pol.PART_ID
) po_arrival ON pi.PART_ID = po_arrival.PART_ID;


-- Also create PLANNED_PURCHASE_ORDERS view from docs/full_ddl_export.sql lines 3867-3931
-- >>> RUN docs/full_ddl_export.sql lines 3867-3931 <<<

-- Wait 1-2 minutes for ACTIVE_ALERTS and OEE_METRICS DTs to refresh.

SET cp9_start = CURRENT_TIMESTAMP();
SET cp9_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

SET cp9_analytics_dts = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'DYNAMIC TABLE' AND TABLE_SCHEMA = 'ANALYTICS');
SET cp9_analytics_views = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = 'ANALYTICS');

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    9, 'ANALYTICS_AND_PROCUREMENT', $cp9_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp9_start, CURRENT_TIMESTAMP()),
    $cp9_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp9_credits_before,
    $cp9_analytics_dts + $cp9_analytics_views,
    CASE WHEN $cp9_analytics_dts >= 2 AND $cp9_analytics_views >= 8 THEN 'PASS' ELSE 'FAIL' END,
    'Analytics DTs: ' || $cp9_analytics_dts || '/2, Analytics Views: ' || $cp9_analytics_views || '/10+'
);


-- ============================================================================
-- CHECKPOINT 10: FATIGUE SCORES + CORTEX SEARCH
-- ============================================================================
SET cp10_start = CURRENT_TIMESTAMP();
SET cp10_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- Fatigue scores (from 06_fatigue_scores.sql)
-- >>> RUN sql/06_fatigue_scores.sql NOW <<<

-- Cortex Search (from 13_cortex_search.sql)
-- >>> RUN sql/13_cortex_search.sql NOW <<<

SET cp10_fatigue = (SELECT COUNT(*) FROM ML_MODELS.FATIGUE_SCORES);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    10, 'FATIGUE_SCORES_AND_CORTEX_SEARCH', $cp10_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp10_start, CURRENT_TIMESTAMP()),
    $cp10_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp10_credits_before,
    $cp10_fatigue + 1,
    CASE WHEN $cp10_fatigue > 0 THEN 'PASS' ELSE 'FAIL' END,
    'Fatigue scores: ' || $cp10_fatigue || ' rows. Cortex Search Service created.'
);


-- ============================================================================
-- CHECKPOINT 11: NOTIFICATIONS + SIMULATION + AUTOMATION
-- ============================================================================
SET cp11_start = CURRENT_TIMESTAMP();
SET cp11_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- >>> RUN sql/19_notifications.sql NOW (notification integration + procs + seed) <<<
-- >>> RUN sql/20_configurable_simulation.sql NOW <<<
-- >>> RUN remaining procs from docs/full_ddl_export.sql:
--     RAW_IT.LOG_APP_NOTIFICATION        (lines 3934-3974)
--     RAW_IT.SEND_MFGPULSE_EMAIL         (if in 19_notifications.sql)
--     RAW_OT.SIMULATE_ALL_FEEDS_RANDOM   (lines 4197-4259)
-- >>> RUN sql/14_automation.sql NOW (DAG tasks + automation procs) <<<

SET cp11_tasks = (SELECT COUNT(*) FROM MFGPULSE_DB.INFORMATION_SCHEMA.TASKS);
SET cp11_notif = (SELECT COUNT(*) FROM RAW_IT.NOTIFICATION_SETTINGS);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    11, 'NOTIFICATIONS_SIMULATION_AUTOMATION', $cp11_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp11_start, CURRENT_TIMESTAMP()),
    $cp11_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp11_credits_before,
    $cp11_tasks + $cp11_notif,
    CASE WHEN $cp11_tasks >= 6 AND $cp11_notif >= 7 THEN 'PASS' ELSE 'FAIL' END,
    'Tasks: ' || $cp11_tasks || '/6+, Notification event types: ' || $cp11_notif || '/7.'
);


-- ============================================================================
-- CHECKPOINT 12: FULL VALIDATION
-- Source: sql/18_validation.sql
-- ============================================================================
SET cp12_start = CURRENT_TIMESTAMP();
SET cp12_credits_before = (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS());

-- Schema validation
SET cp12_schemas = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA
    WHERE SCHEMA_NAME IN ('RAW_OT','RAW_IT','CURATED','ML_FEATURES','ML_MODELS','ANALYTICS','AGENT'));

-- Object counts
SET cp12_base_tables = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC'));
SET cp12_dts = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE='DYNAMIC TABLE');
SET cp12_views = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC'));
SET cp12_procs = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.PROCEDURES
    WHERE PROCEDURE_SCHEMA NOT IN ('INFORMATION_SCHEMA','PUBLIC'));

-- Data integrity
SET cp12_lp = (SELECT COUNT(*) FROM ML_MODELS.LIVE_PREDICTIONS);
SET cp12_alerts = (SELECT COUNT(*) FROM ANALYTICS.ACTIVE_ALERTS);
SET cp12_oee = (SELECT COUNT(*) FROM ANALYTICS.OEE_METRICS);

SET cp12_pass = (CASE
    WHEN $cp12_schemas = 7 AND $cp12_base_tables >= 21 AND $cp12_dts >= 13
         AND $cp12_views >= 20 AND $cp12_lp = 10
    THEN 'PASS' ELSE 'FAIL' END);

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    12, 'FULL_VALIDATION', $cp12_start, CURRENT_TIMESTAMP(),
    DATEDIFF('second', $cp12_start, CURRENT_TIMESTAMP()),
    $cp12_credits_before, (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()),
    (SELECT MFGPULSE_DB.PUBLIC.GET_WH_CREDITS()) - $cp12_credits_before,
    0, $cp12_pass,
    'Schemas=' || $cp12_schemas || '/7 Tables=' || $cp12_base_tables || '/21+ DTs=' || $cp12_dts
    || '/13 Views=' || $cp12_views || '/20+ Predictions=' || $cp12_lp || '/10 Alerts='
    || $cp12_alerts || ' OEE=' || $cp12_oee || ' Procs=' || $cp12_procs
);


-- ============================================================================
-- CHECKPOINT 13: CORTEX AGENT (manual step)
-- Deploy using the Cortex Agent Studio CLI or Snowsight UI:
--   snow cortex agent-studio sv-deploy cortex_project/MAINTENANCE_SEMANTIC_VIEW.sv.yaml
--   snow cortex agent-studio agent-deploy cortex_project/MAINTENANCE_COPILOT_agent.yaml
-- ============================================================================
-- After deploying, log the checkpoint:

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    13, 'CORTEX_AGENT', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
    0, 0, 0, 0, 2, 'SKIP',
    'Manual step: Deploy Semantic View + Cortex Agent from cortex_project/. Mark PASS after completion.'
);


-- ============================================================================
-- CHECKPOINT 14: STREAMLIT APP (manual step)
-- Open MFGPulse_AI_App/ in Snowsight Workspaces.
-- The app auto-deploys via snowflake.yml configuration.
-- Verify all 8 pages render correctly.
-- ============================================================================

INSERT INTO MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG VALUES (
    14, 'STREAMLIT_APP', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
    0, 0, 0, 0, 1, 'SKIP',
    'Manual step: Open MFGPulse_AI_App/ in Snowsight. Mark PASS after verification.'
);


-- ============================================================================
-- DEPLOYMENT SUMMARY
-- ============================================================================
SELECT
    CHECKPOINT_ID AS CP,
    CHECKPOINT_NAME AS PHASE,
    DURATION_SEC AS SECONDS,
    ROUND(CREDITS_USED, 6) AS CREDITS,
    OBJECTS_CREATED AS OBJECTS,
    VALIDATION AS STATUS,
    DETAILS
FROM MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG
ORDER BY CHECKPOINT_ID;

-- Total
SELECT
    COUNT(*) AS CHECKPOINTS,
    SUM(DURATION_SEC) AS TOTAL_SECONDS,
    ROUND(SUM(DURATION_SEC) / 60.0, 1) AS TOTAL_MINUTES,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    SUM(OBJECTS_CREATED) AS TOTAL_OBJECTS,
    SUM(CASE WHEN VALIDATION = 'PASS' THEN 1 ELSE 0 END) AS PASSED,
    SUM(CASE WHEN VALIDATION = 'FAIL' THEN 1 ELSE 0 END) AS FAILED,
    SUM(CASE WHEN VALIDATION = 'SKIP' THEN 1 ELSE 0 END) AS MANUAL
FROM MFGPULSE_DB.PUBLIC.DEPLOYMENT_LOG;
