-- ============================================================================
-- MFGPulse AI: 01 Infrastructure
-- Database, schemas, warehouse, resource monitor
-- ============================================================================

CREATE DATABASE IF NOT EXISTS MFGPULSE_DB;

USE DATABASE MFGPULSE_DB;

CREATE SCHEMA IF NOT EXISTS RAW_OT;
CREATE SCHEMA IF NOT EXISTS RAW_IT;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS ML_FEATURES;
CREATE SCHEMA IF NOT EXISTS ML_MODELS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS AGENT;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE RESOURCE MONITOR IF NOT EXISTS MFGPULSE_CREDIT_GUARD
    WITH CREDIT_QUOTA = 250
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = MFGPULSE_CREDIT_GUARD;
