-- ============================================================================
-- MFGPulse AI: Cross-Account Transfer Script
-- Transfers MFGPULSE_DB to target account QEIPXIJ.NB44213
--
-- Source: DGTEFBJ.JB14149 (BB99219, AWS_US_EAST_2)
-- Target: QEIPXIJ.NB44213 (different organization)
--
-- Since the accounts are in DIFFERENT organizations, replication groups
-- are not available. Two options are provided:
--
--   OPTION B: Data Sharing (read-only access, zero-copy, instant)
--   OPTION C: Standalone Deploy (full writable copy on target)
--
-- ============================================================================


-- ############################################################################
-- OPTION B: DATA SHARING (read-only, zero-copy)
-- ############################################################################
--
-- Creates a Snowflake share that gives the target account read-only access
-- to all tables and views. Zero data movement — consumers query live data.
--
-- Limitations:
--   - Read-only: target cannot INSERT/UPDATE/DELETE
--   - No UDFs, procedures, tasks, streams, ML models, or Cortex services
--   - Target queries run on target's warehouse but read source's data
--   - Views referencing UDFs will NOT work (UDFs don't share)
--
-- Best for: evaluation, demo access, read-only analytics on target account
-- ############################################################################

-- Run on SOURCE account (BB99219) as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;
USE DATABASE MFGPULSE_DB;

-- Step B1: Create the share
CREATE OR REPLACE SHARE MFGPULSE_SHARE
    COMMENT = 'MFGPulse AI — Predictive Maintenance & OEE Command Center (read-only)';

-- Step B2: Grant database and schema usage
GRANT USAGE ON DATABASE MFGPULSE_DB TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.RAW_OT TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.RAW_IT TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.CURATED TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.ML_FEATURES TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.ML_MODELS TO SHARE MFGPULSE_SHARE;
GRANT USAGE ON SCHEMA MFGPULSE_DB.ANALYTICS TO SHARE MFGPULSE_SHARE;

-- Step B3: Grant SELECT on all tables
-- RAW_OT
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_OT.ASSET_MASTER TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_OT.SENSOR_METADATA TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_OT.SENSOR_READINGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_OT.AMBIENT_CONDITIONS TO SHARE MFGPULSE_SHARE;

-- RAW_IT
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.WORK_ORDERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.MAINTENANCE_LOGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PARTS_INVENTORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PRODUCTION_OUTPUT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.SUPPLIERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.USERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDERS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PURCHASE_ORDER_LINES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.SHIFT_SCHEDULE TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.APP_NOTIFICATIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.NOTIFICATION_SETTINGS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PART_RESERVATIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.SIMULATION_CONFIG TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.RAW_IT.PART_SUPPLIERS TO SHARE MFGPULSE_SHARE;

-- CURATED (dynamic tables appear as tables for sharing)
GRANT SELECT ON TABLE MFGPULSE_DB.CURATED.SENSOR_WITH_CONTEXT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.CURATED.ASSET_HEALTH_CURRENT TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.CURATED.FAILURE_HISTORY TO SHARE MFGPULSE_SHARE;

-- ML_FEATURES (dynamic tables)
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.ROLLING_STATS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.SENSOR_INTERACTIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.PHYSICS_COMPOSITE TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.TEMPORAL_MEMORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.CROSS_DOMAIN TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.FLEET_COMPARISON TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_FEATURES.LABELED_DATA TO SHARE MFGPULSE_SHARE;

-- ML_MODELS
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.LIVE_PREDICTIONS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.FATIGUE_SCORES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.ANOMALY_SCORES TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.MODEL_REGISTRY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.FEEDBACK_LOG TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ML_MODELS.DRIFT_COMPARISON TO SHARE MFGPULSE_SHARE;

-- ANALYTICS (dynamic tables + tables)
GRANT SELECT ON TABLE MFGPULSE_DB.ANALYTICS.ACTIVE_ALERTS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ANALYTICS.OEE_METRICS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ANALYTICS.SHIFT_HANDOVER_HISTORY TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ANALYTICS.KPI_SNAPSHOTS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON TABLE MFGPULSE_DB.ANALYTICS.ALERT_HISTORY TO SHARE MFGPULSE_SHARE;

-- Step B4: Share views (must be SECURE to share)
-- Make views secure first, then grant
ALTER VIEW MFGPULSE_DB.ML_MODELS.DRIFT_METRICS SET SECURE;
ALTER VIEW MFGPULSE_DB.ML_MODELS.MODEL_ACCURACY_LIVE SET SECURE;

-- ML_MODELS views (no UDF dependencies)
GRANT SELECT ON VIEW MFGPULSE_DB.ML_MODELS.DRIFT_METRICS TO SHARE MFGPULSE_SHARE;
GRANT SELECT ON VIEW MFGPULSE_DB.ML_MODELS.MODEL_ACCURACY_LIVE TO SHARE MFGPULSE_SHARE;

-- Note: Views referencing UDFs (e.g., LIVE_PREDICTIONS_WITH_ANOMALY, PREDICTIONS_WITH_COST)
-- cannot be shared because UDFs don't transfer via shares. The target account gets the
-- underlying tables (LIVE_PREDICTIONS, FATIGUE_SCORES, etc.) and can recreate views locally.

-- Step B5: Add the target account to the share
-- Use the account LOCATOR (NB44213), not the org-qualified name
ALTER SHARE MFGPULSE_SHARE ADD ACCOUNTS = QEIPXIJ.NB44213;

-- Verify
SHOW GRANTS TO SHARE MFGPULSE_SHARE;


-- ============================================================================
-- Run on TARGET account (QEIPXIJ.NB44213) as ACCOUNTADMIN
-- ============================================================================

-- Step B6: Create database from share
-- >>> SWITCH TO TARGET ACCOUNT <<<
-- USE ROLE ACCOUNTADMIN;
-- CREATE DATABASE MFGPULSE_DB_SHARED FROM SHARE DGTEFBJ.JB14149.MFGPULSE_SHARE;
--
-- -- Verify
-- SELECT COUNT(*) FROM MFGPULSE_DB_SHARED.ML_MODELS.LIVE_PREDICTIONS;
-- SELECT * FROM MFGPULSE_DB_SHARED.RAW_OT.ASSET_MASTER;



-- ############################################################################
-- OPTION C: STANDALONE DEPLOY (full writable copy)
-- ############################################################################
--
-- Deploys the entire MFGPULSE_DB from scratch on the target account
-- using the deploy_one_time_consolidated.sql script. This gives the target
-- a fully independent, writable copy with all objects including:
--   - All tables with generated data (172K+ sensor readings)
--   - All dynamic tables, views, procedures, UDFs
--   - Native ML models (trained fresh)
--   - Cortex Search, Agent, Semantic View
--   - Task DAG (automation)
--
-- Estimated time: ~20-30 minutes
-- Estimated cost: ~1-2 credits
--
-- Best for: independent environment, full write access, complete feature parity
-- ############################################################################

-- Run on TARGET account (QEIPXIJ.NB44213)

-- >>> SWITCH TO TARGET ACCOUNT <<<
-- USE ROLE ACCOUNTADMIN;

-- Step C1: Create warehouses
-- CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
--     WITH WAREHOUSE_SIZE = 'XSMALL'
--     AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
--
-- CREATE WAREHOUSE IF NOT EXISTS MFGPULSE_AUTOMATION_WH
--     WITH WAREHOUSE_SIZE = 'XSMALL'
--     AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
--
-- USE WAREHOUSE COMPUTE_WH;

-- Step C2: Run the full deploy script
-- Copy the entire contents of sql/deploy_one_time_consolidated.sql to a
-- SQL worksheet on the target account and execute it.
-- This creates the database, all schemas, tables, seed data, sensor data,
-- dynamic tables, UDFs, procedures, views, and analytics layer.

-- Step C3: Train native ML models
-- After deploy_one_time_consolidated.sql completes:
-- GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA MFGPULSE_DB.ML_MODELS TO ROLE ACCOUNTADMIN;
-- GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA MFGPULSE_DB.ML_MODELS TO ROLE ACCOUNTADMIN;
-- GRANT CREATE SNOWFLAKE.ML.ANOMALY_DETECTION ON SCHEMA MFGPULSE_DB.ML_MODELS TO ROLE ACCOUNTADMIN;
--
-- CREATE SNOWFLAKE.ML.CLASSIFICATION ML_MODELS.NATIVE_FAILURE_MODE_CLASSIFIER(
--     INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML_FEATURES.TRAIN_FAILURE_MODE'),
--     TARGET_COLNAME => 'FAILURE_MODE');
--
-- CREATE SNOWFLAKE.ML.CLASSIFICATION ML_MODELS.NATIVE_DEGRADATION_STAGER(
--     INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML_FEATURES.TRAIN_TRAJECTORY_3CLASS'),
--     TARGET_COLNAME => 'STAGE_3CLASS');

-- Step C4: Deploy Cortex Agent + Semantic View
-- Upload cortex_project/ directory to target workspace, then:
-- snow cortex agent-studio sv-deploy cortex_project/MAINTENANCE_SEMANTIC_VIEW.sv.yaml
-- snow cortex agent-studio agent-deploy cortex_project/MAINTENANCE_COPILOT_agent.yaml

-- Step C5: Deploy Streamlit app
-- Upload MFGPulse_AI_App/ directory to target workspace and run from Snowsight.

-- Step C6: (Optional) Resume automation DAG
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_CONVERT_PPOS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_SNAPSHOT_KPIS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_ARCHIVE_ALERTS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_CHECK_DRIFT RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_GENERATE_POS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_GENERATE_WOS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_REFRESH_DTS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_REFRESH_FATIGUE RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.DAG_CHECK_FRESHNESS RESUME;
-- ALTER TASK MFGPULSE_DB.ANALYTICS.MFGPULSE_AUTOMATION_DAG RESUME;

-- Step C7: Validate
-- Run sql/deployment_report.sql on target to verify all objects are present.
